from __future__ import annotations

from pathlib import Path


SRC_DIR = Path(__file__).resolve().parent
STATISTICS_DIR = SRC_DIR.parent
DATA_DIR = STATISTICS_DIR / "data"
OUT_DIR = STATISTICS_DIR / "out"
MODELS_DIR = OUT_DIR / "models"

DEFAULT_PRICE_JSON_PATH = DATA_DIR / "daily_price.json"
DEFAULT_AMOUNTS_JSON_PATH = DATA_DIR / "daily_amounts.json"
DEFAULT_TX_SIZE_JSON_PATH = DATA_DIR / "daily_tx_size.json"

DEFAULT_FEATURES_CSV_PATH = OUT_DIR / "features.csv"
DEFAULT_ONCHAIN_FEATURES_CSV_PATH = OUT_DIR / "onchain_features.csv"
DEFAULT_TARGETS_CSV_PATH = OUT_DIR / "targets.csv"
DEFAULT_STATES_CSV_PATH = OUT_DIR / "states.csv"
DEFAULT_BOTTOM_DATASET_CSV_PATH = OUT_DIR / "swing_bottom" / "bottom_dataset.csv"
DEFAULT_REVERSAL_ZONE_DATASET_CSV_PATH = OUT_DIR / "swing_bottom" / "reversal_zone_dataset.csv"
DEFAULT_BOTTOM_MODEL_PREDICTIONS_CSV_PATH = OUT_DIR / "swing_bottom" / "bottom_model_predictions.csv"
DEFAULT_BOTTOM_MODEL_METRICS_CSV_PATH = OUT_DIR / "swing_bottom" / "bottom_model_metrics.csv"
DEFAULT_REVERSAL_ZONE_PREDICTIONS_CSV_PATH = OUT_DIR / "swing_bottom" / "reversal_zone_predictions.csv"
DEFAULT_REVERSAL_ZONE_METRICS_CSV_PATH = OUT_DIR / "swing_bottom" / "reversal_zone_metrics.csv"
DEFAULT_REVERSAL_PROXIMITY_PREDICTIONS_CSV_PATH = OUT_DIR / "swing_bottom" / "reversal_proximity_predictions.csv"
DEFAULT_REVERSAL_PROXIMITY_METRICS_CSV_PATH = OUT_DIR / "swing_bottom" / "reversal_proximity_metrics.csv"
DEFAULT_SWING_EXTREME_TIMING_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_extreme_timing.csv"
DEFAULT_SWING_EXTREME_TIMING_SWING_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_extreme_timing_swing_summary.csv"
DEFAULT_SWING_EXTREME_TIMING_THRESHOLDS_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_extreme_timing_thresholds.csv"
DEFAULT_SWING_EXTREME_TIMING_ABLATION_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_extreme_timing_ablation.csv"
DEFAULT_BUY_SIDE_EXPLORATION_SCORES_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_exploration_scores.csv"
DEFAULT_BUY_SIDE_EXPLORATION_COMPARISON_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_exploration_comparison.csv"
DEFAULT_BUY_SIDE_EXPLORATION_SWING_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_exploration_swing_summary.csv"
DEFAULT_BUY_SIDE_HYBRID_SCORES_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_hybrid_scores.csv"
DEFAULT_BUY_SIDE_HYBRID_COMPARISON_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_hybrid_comparison.csv"
DEFAULT_BUY_SIDE_HYBRID_SWING_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_hybrid_swing_summary.csv"
DEFAULT_BUY_SIDE_HYBRID_VALIDATION_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_hybrid_validation.csv"
DEFAULT_BUY_SIDE_HYBRID_VALIDATION_DETAIL_CSV_PATH = OUT_DIR / "swing_bottom" / "buy_side_hybrid_validation_detail.csv"
DEFAULT_SWING_DECISION_LAYER_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_decision_layer.csv"
DEFAULT_SWING_DECISION_LAYER_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_decision_layer_summary.csv"
DEFAULT_SWING_PLAYBOOK_LAYER_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_playbook_layer.csv"
DEFAULT_SWING_PLAYBOOK_LAYER_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_playbook_layer_summary.csv"
DEFAULT_SWING_PLAYBOOK_VALIDATION_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_playbook_validation.csv"
DEFAULT_SWING_PLAYBOOK_VALIDATION_DETAIL_CSV_PATH = OUT_DIR / "swing_bottom" / "swing_playbook_validation_detail.csv"
DEFAULT_STRATEGY_TRANSLATION_CSV_PATH = OUT_DIR / "swing_bottom" / "strategy_translation_layer.csv"
DEFAULT_STRATEGY_TRANSLATION_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "strategy_translation_summary.csv"
DEFAULT_RULE_LAYER_CSV_PATH = OUT_DIR / "swing_bottom" / "rule_layer.csv"
DEFAULT_RULE_LAYER_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "rule_layer_summary.csv"
DEFAULT_RULE_LAYER_CALIBRATION_CSV_PATH = OUT_DIR / "swing_bottom" / "rule_layer_calibration.csv"
DEFAULT_RULE_LAYER_CALIBRATION_DETAIL_CSV_PATH = OUT_DIR / "swing_bottom" / "rule_layer_calibration_detail.csv"
DEFAULT_SIGNAL_LAYER_CSV_PATH = OUT_DIR / "swing_bottom" / "signal_layer.csv"
DEFAULT_SIGNAL_LAYER_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "signal_layer_summary.csv"
DEFAULT_SIGNAL_OUTCOMES_CSV_PATH = OUT_DIR / "swing_bottom" / "signal_outcomes.csv"
DEFAULT_SIGNAL_OUTCOMES_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "signal_outcomes_summary.csv"
DEFAULT_LONG_SIGNAL_REFINEMENT_CSV_PATH = OUT_DIR / "swing_bottom" / "long_signal_refinement.csv"
DEFAULT_LONG_SIGNAL_REFINEMENT_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "long_signal_refinement_summary.csv"
DEFAULT_FINAL_LONG_SIGNAL_CONDITIONING_CSV_PATH = OUT_DIR / "swing_bottom" / "final_long_signal_conditioning.csv"
DEFAULT_FINAL_LONG_SIGNAL_CONDITIONING_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "final_long_signal_conditioning_summary.csv"
DEFAULT_MINIMAL_STRATEGY_TRADES_CSV_PATH = OUT_DIR / "swing_bottom" / "minimal_strategy_trades.csv"
DEFAULT_MINIMAL_STRATEGY_SUMMARY_CSV_PATH = OUT_DIR / "swing_bottom" / "minimal_strategy_summary.csv"
DEFAULT_CAUSAL_BOTTOM_PROXY_COMPARISON_CSV_PATH = OUT_DIR / "swing_bottom" / "causal_bottom_proxy_comparison.csv"
DEFAULT_CAUSAL_BOTTOM_PROXY_MEMBERSHIP_CSV_PATH = OUT_DIR / "swing_bottom" / "causal_bottom_proxy_membership.csv"
DEFAULT_HMM_PACK_PATH = MODELS_DIR / "hmm_pack.joblib"
DEFAULT_HAZARD_PACK_PATH = MODELS_DIR / "hazard_pack.joblib"
