from __future__ import annotations

from pathlib import Path
from typing import TypedDict

from src.path_config import OUT_DIR


class ViewDefinition(TypedDict, total=False):
    label: str
    description: str
    path: str
    scores: list[str]
    components: list[str]
    labels: list[str]
    diagnostics: list[str]
    default_scores: list[str]
    default_components: list[str]
    default_labels: list[str]
    default_threshold: float


def _relative(path: Path) -> str:
    return str(path)


VIEW_REGISTRY: dict[str, ViewDefinition] = {
    "swing_extreme_timing": {
        "label": "Swing Extreme Timing",
        "description": "Combined phase, analog, and exhaustion timing layer for buyable and sellable swing-extreme zones.",
        "path": _relative(OUT_DIR / "swing_bottom" / "swing_extreme_timing.csv"),
        "scores": [
            "buy_extreme_timing_score",
            "sell_extreme_timing_score",
            "buy_fixed_extreme_timing_score",
            "sell_fixed_extreme_timing_score",
        ],
        "components": [
            "buy_phase_prob",
            "sell_phase_prob",
            "buy_analog_prob",
            "sell_analog_prob",
            "buy_analog_prob_strict",
            "sell_analog_prob_strict",
            "buy_exhaustion_score",
            "sell_exhaustion_score",
            "buy_phase_analog_score",
            "sell_phase_analog_score",
            "buy_phase_exhaustion_score",
            "sell_phase_exhaustion_score",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "live_swing_direction",
            "days_since_last_pivot",
            "distance_from_last_pivot_pct",
            "distance_from_last_pivot_atr_units",
            "current_swing_age_pct_of_median",
            "current_swing_size_pct_of_median",
            "buy_analog_median_days",
            "sell_analog_median_days",
            "buy_analog_match_count",
            "sell_analog_match_count",
            "dist_to_current_down_swing_low_pct",
            "dist_to_current_up_swing_high_pct",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
        ],
        "default_scores": [
            "buy_extreme_timing_score",
            "sell_extreme_timing_score",
            "buy_fixed_extreme_timing_score",
            "sell_fixed_extreme_timing_score",
        ],
        "default_components": [
            "buy_phase_prob",
            "buy_analog_prob",
            "buy_exhaustion_score",
            "sell_phase_prob",
            "sell_analog_prob",
            "sell_exhaustion_score",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.75,
    },
    "reversal_zone_dataset": {
        "label": "Reversal Zone Dataset",
        "description": "Daily causal feature surface with good-enough buy-zone and sell-zone labels tied to confirmed swings.",
        "path": _relative(OUT_DIR / "swing_bottom" / "reversal_zone_dataset.csv"),
        "scores": [],
        "components": [
            "dist_to_current_down_swing_low_pct",
            "dist_to_current_up_swing_high_pct",
            "current_swing_age_pct_of_median",
            "current_swing_size_pct_of_median",
        ],
        "labels": [
            "buy_zone_bottom_10pct_of_range",
            "buy_zone_bottom_5pct_of_range",
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_top_10pct_of_range",
            "sell_zone_top_5pct_of_range",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "live_swing_direction",
            "days_since_last_pivot",
            "distance_from_last_pivot_pct",
            "distance_from_last_pivot_atr_units",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
            "dist_to_current_down_swing_low_range_frac",
            "dist_to_current_up_swing_high_range_frac",
        ],
        "default_scores": [],
        "default_components": [
            "dist_to_current_down_swing_low_pct",
            "dist_to_current_up_swing_high_pct",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.50,
    },
    "reversal_zone_predictions": {
        "label": "Reversal Zone Predictions",
        "description": "Corrected leakage-safe buy and sell zone probabilities with held-out evaluation labels.",
        "path": _relative(OUT_DIR / "swing_bottom" / "reversal_zone_predictions.csv"),
        "scores": [
            "buy_predicted_probability",
            "sell_predicted_probability",
        ],
        "components": [],
        "labels": [
            "buy_primary_target",
            "buy_strict_target",
            "sell_primary_target",
            "sell_strict_target",
        ],
        "diagnostics": [
            "dist_to_current_down_swing_low_pct",
            "dist_to_current_up_swing_high_pct",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
        ],
        "default_scores": [
            "buy_predicted_probability",
            "sell_predicted_probability",
        ],
        "default_components": [],
        "default_labels": [
            "buy_primary_target",
            "sell_primary_target",
        ],
        "default_threshold": 0.50,
    },
    "reversal_proximity_predictions": {
        "label": "Reversal Proximity Predictions",
        "description": "Continuous buy-side and sell-side proximity estimates inside confirmed swings.",
        "path": _relative(OUT_DIR / "swing_bottom" / "reversal_proximity_predictions.csv"),
        "scores": [
            "predicted_buy_distance",
            "predicted_sell_distance",
        ],
        "components": [],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "true_buy_distance",
            "true_sell_distance",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
        ],
        "default_scores": [
            "predicted_buy_distance",
            "predicted_sell_distance",
        ],
        "default_components": [],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.00,
    },
    "buy_side_exploration": {
        "label": "Buy-Side Exploration",
        "description": "Bounded buy-side swing-low timing sprint comparing analog, exhaustion, ranking, and candle-memory approaches.",
        "path": _relative(OUT_DIR / "swing_bottom" / "buy_side_exploration_scores.csv"),
        "scores": [
            "buy_fixed_extreme_timing_score",
            "buy_phase_prob",
            "buy_extreme_timing_score",
            "buy_analog_overhaul_score",
            "buy_exhaustion_redesign_score",
            "buy_ordinal_ranking_score",
            "buy_candle_pattern_memory_score",
            "buy_consensus_phase_any_score",
        ],
        "components": [
            "buy_analog_overhaul_score",
            "buy_exhaustion_redesign_score",
            "buy_ordinal_prob_usable_5pct",
            "buy_ordinal_prob_near_3pct",
            "buy_candle_pattern_memory_score",
            "buy_consensus_phase_any_score",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
        ],
        "diagnostics": [
            "live_swing_direction",
            "days_since_last_pivot",
            "distance_from_last_pivot_pct",
            "current_swing_age_pct_of_median",
            "current_swing_size_pct_of_median",
            "buy_analog_overhaul_match_count",
            "buy_candle_pattern_match_count",
            "dist_to_current_down_swing_low_pct",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
        ],
        "default_scores": [
            "buy_fixed_extreme_timing_score",
            "buy_analog_overhaul_score",
            "buy_exhaustion_redesign_score",
            "buy_ordinal_ranking_score",
            "buy_candle_pattern_memory_score",
        ],
        "default_components": [
            "buy_analog_overhaul_score",
            "buy_exhaustion_redesign_score",
            "buy_ordinal_prob_usable_5pct",
            "buy_ordinal_prob_near_3pct",
            "buy_candle_pattern_memory_score",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
        ],
        "default_threshold": 0.70,
    },
    "buy_side_hybrid": {
        "label": "Buy-Side Hybrid",
        "description": "Narrow buy-side hybrid pass combining fixed baseline, redesigned exhaustion, and ordinal ranking.",
        "path": _relative(OUT_DIR / "swing_bottom" / "buy_side_hybrid_scores.csv"),
        "scores": [
            "buy_fixed_extreme_timing_score",
            "buy_exhaustion_redesign_score",
            "buy_ordinal_ranking_score",
            "buy_hybrid_weighted_balanced_score",
            "buy_hybrid_rank_local_score",
            "buy_hybrid_learned_combo_score",
            "buy_hybrid_two_stage_score",
        ],
        "components": [
            "buy_fixed_extreme_timing_score",
            "buy_exhaustion_redesign_score",
            "buy_ordinal_ranking_score",
            "buy_hybrid_weighted_balanced_score",
            "buy_hybrid_rank_local_score",
            "buy_hybrid_learned_combo_score",
            "buy_hybrid_two_stage_score",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
        ],
        "diagnostics": [
            "live_swing_direction",
            "days_since_last_pivot",
            "distance_from_last_pivot_pct",
            "current_swing_age_pct_of_median",
            "current_swing_size_pct_of_median",
            "dist_to_current_down_swing_low_pct",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
        ],
        "default_scores": [
            "buy_fixed_extreme_timing_score",
            "buy_hybrid_weighted_balanced_score",
            "buy_hybrid_rank_local_score",
            "buy_hybrid_learned_combo_score",
            "buy_hybrid_two_stage_score",
        ],
        "default_components": [
            "buy_exhaustion_redesign_score",
            "buy_ordinal_ranking_score",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
        ],
        "default_threshold": 0.70,
    },
    "swing_decision_layer": {
        "label": "Swing Decision Layer",
        "description": "Combined buy/sell timing decision states with dominance, conflict, and clarity scores.",
        "path": _relative(OUT_DIR / "swing_bottom" / "swing_decision_layer.csv"),
        "scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "buy_dominance_score",
            "sell_dominance_score",
            "edge_clarity_score",
            "conflict_score",
        ],
        "components": [
            "timing_score_spread",
            "timing_score_intensity",
            "timing_score_overlap",
            "buy_dominance_score",
            "sell_dominance_score",
            "edge_clarity_score",
            "conflict_score",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "decision_state",
            "score_interaction_bucket",
            "buy_score_band",
            "sell_score_band",
            "live_swing_direction",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
            "decision_state_age_days",
            "decision_state_run_length_days",
            "dist_to_current_down_swing_low_pct",
            "dist_to_current_up_swing_high_pct",
        ],
        "default_scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "edge_clarity_score",
            "conflict_score",
        ],
        "default_components": [
            "timing_score_spread",
            "buy_dominance_score",
            "sell_dominance_score",
            "timing_score_overlap",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.70,
    },
    "swing_playbook_layer": {
        "label": "Swing Playbook Layer",
        "description": "Human-readable playbook interpretation built from swing decision states.",
        "path": _relative(OUT_DIR / "swing_bottom" / "swing_playbook_layer.csv"),
        "scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "edge_clarity_score",
            "conflict_score",
            "buy_dominance_score",
            "sell_dominance_score",
        ],
        "components": [
            "timing_score_spread",
            "timing_score_intensity",
            "timing_score_overlap",
            "edge_clarity_score",
            "conflict_score",
            "playbook_is_clear",
            "playbook_is_caution",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "decision_state",
            "playbook_label",
            "playbook_bias",
            "playbook_attention_level",
            "playbook_note",
            "score_interaction_bucket",
            "live_swing_direction",
            "playbook_age_days",
            "playbook_run_length_days",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
        ],
        "default_scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "edge_clarity_score",
            "conflict_score",
        ],
        "default_components": [
            "timing_score_spread",
            "buy_dominance_score",
            "sell_dominance_score",
            "playbook_is_clear",
            "playbook_is_caution",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.70,
    },
    "strategy_translation_layer": {
        "label": "Strategy Translation Layer",
        "description": "Operational structural states translated from the promoted playbook layer.",
        "path": _relative(OUT_DIR / "swing_bottom" / "strategy_translation_layer.csv"),
        "scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "edge_clarity_score",
            "conflict_score",
            "readiness_flag",
            "caution_flag",
            "invalidation_flag",
        ],
        "components": [
            "timing_score_spread",
            "timing_score_intensity",
            "timing_score_overlap",
            "buy_dominance_score",
            "sell_dominance_score",
            "operational_is_active_context",
            "stand_aside_flag",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "decision_state",
            "playbook_label",
            "playbook_attention_level",
            "operational_state",
            "operational_bias",
            "operational_note",
            "score_interaction_bucket",
            "live_swing_direction",
            "operational_state_age_days",
            "operational_state_run_length_days",
        ],
        "default_scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "readiness_flag",
            "caution_flag",
            "invalidation_flag",
        ],
        "default_components": [
            "timing_score_spread",
            "edge_clarity_score",
            "conflict_score",
            "operational_is_active_context",
            "stand_aside_flag",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.70,
    },
    "rule_layer": {
        "label": "Minimal Rule Layer",
        "description": "Explicit permission, wait, block, and invalidation states derived from operational context.",
        "path": _relative(OUT_DIR / "swing_bottom" / "rule_layer.csv"),
        "scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "long_permission_flag",
            "sell_derisk_permission_flag",
            "confirmation_needed_flag",
            "block_action_flag",
            "invalidation_active_flag",
        ],
        "components": [
            "timing_score_spread",
            "edge_clarity_score",
            "conflict_score",
            "readiness_flag",
            "caution_flag",
            "rule_is_permission",
            "rule_is_block",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "decision_state",
            "playbook_label",
            "operational_state",
            "operational_bias",
            "rule_state",
            "rule_note",
            "operational_state_age_days",
            "rule_state_age_days",
            "rule_state_run_length_days",
        ],
        "default_scores": [
            "long_permission_flag",
            "sell_derisk_permission_flag",
            "confirmation_needed_flag",
            "block_action_flag",
            "invalidation_active_flag",
        ],
        "default_components": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "timing_score_spread",
            "edge_clarity_score",
            "conflict_score",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.70,
    },
    "signal_layer": {
        "label": "Signal Realization Layer",
        "description": "Discrete structural signal onset, continuation, and invalidation events derived from the calibrated rule layer.",
        "path": _relative(OUT_DIR / "swing_bottom" / "signal_layer.csv"),
        "scores": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "long_signal_event_flag",
            "sell_signal_event_flag",
            "signal_continuation_flag",
            "signal_invalidation_event_flag",
            "signal_active_flag",
        ],
        "components": [
            "timing_score_spread",
            "edge_clarity_score",
            "conflict_score",
            "long_permission_flag",
            "sell_derisk_permission_flag",
            "confirmation_needed_flag",
            "block_action_flag",
            "signal_reactivation_flag",
        ],
        "labels": [
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
            "sell_zone_within_5pct_below_high",
            "sell_zone_within_3pct_below_high",
        ],
        "diagnostics": [
            "decision_state",
            "playbook_label",
            "operational_state",
            "rule_state",
            "signal_state",
            "signal_side",
            "signal_note",
            "rule_state_age_days",
            "signal_context_age_days",
            "signal_context_run_length_days",
        ],
        "default_scores": [
            "long_signal_event_flag",
            "sell_signal_event_flag",
            "signal_continuation_flag",
            "signal_invalidation_event_flag",
            "signal_active_flag",
        ],
        "default_components": [
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "timing_score_spread",
            "edge_clarity_score",
            "conflict_score",
        ],
        "default_labels": [
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ],
        "default_threshold": 0.70,
    },
}
