from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd

from src.path_config import (
    DEFAULT_BUY_SIDE_HYBRID_SCORES_CSV_PATH,
    DEFAULT_FEATURES_CSV_PATH,
    DEFAULT_ONCHAIN_FEATURES_CSV_PATH,
    DEFAULT_REVERSAL_ZONE_DATASET_CSV_PATH,
    DEFAULT_RULE_LAYER_CSV_PATH,
    DEFAULT_SIGNAL_LAYER_CSV_PATH,
    DEFAULT_STATES_CSV_PATH,
    DEFAULT_STRATEGY_TRANSLATION_CSV_PATH,
    DEFAULT_SWING_DECISION_LAYER_CSV_PATH,
    DEFAULT_SWING_EXTREME_TIMING_CSV_PATH,
    DEFAULT_SWING_PLAYBOOK_LAYER_CSV_PATH,
    DEFAULT_TARGETS_CSV_PATH,
    OUT_DIR,
)
from src.research.v4_iteration.dashboard.view_registry import VIEW_REGISTRY


@dataclass(frozen=True)
class CsvContract:
    name: str
    path: Path
    required_columns: tuple[str, ...]
    group: str
    description: str
    date_column: str | None = "date"
    require_unique_date: bool = True
    require_sorted_date: bool = True
    forbidden_prefixes: tuple[str, ...] = ()
    allowed_missing: bool = False


@dataclass(frozen=True)
class ContractResult:
    name: str
    group: str
    status: str
    path: Path | None
    message: str

    @property
    def is_failure(self) -> bool:
        return self.status == "FAIL"


FUTURE_DERIVED_PREFIXES: tuple[str, ...] = (
    "next_",
    "containing_",
    "buy_zone_",
    "sell_zone_",
    "dist_to_current_",
    "current_confirmed_",
)


FEATURE_SURFACE_CONTRACTS: tuple[CsvContract, ...] = (
    CsvContract(
        name="features",
        group="features",
        path=DEFAULT_FEATURES_CSV_PATH,
        description="Primary normalized causal price/model feature surface.",
        required_columns=("date", "open", "high", "low", "close", "volume"),
        forbidden_prefixes=FUTURE_DERIVED_PREFIXES,
    ),
    CsvContract(
        name="onchain_features",
        group="features",
        path=DEFAULT_ONCHAIN_FEATURES_CSV_PATH,
        description="Normalized causal on-chain feature surface.",
        required_columns=(
            "date",
            "ONCHAIN_AMOUNT_LOG",
            "ONCHAIN_WHALE_SHARE",
            "ONCHAIN_DOMINANCE",
        ),
        forbidden_prefixes=FUTURE_DERIVED_PREFIXES,
    ),
    CsvContract(
        name="targets",
        group="features",
        path=DEFAULT_TARGETS_CSV_PATH,
        description="Productive target surface when generated by the default pipeline.",
        required_columns=("date",),
        allowed_missing=True,
    ),
    CsvContract(
        name="states",
        group="features",
        path=DEFAULT_STATES_CSV_PATH,
        description="Productive state surface when generated by the default pipeline.",
        required_columns=("date",),
        allowed_missing=True,
    ),
)


SWING_FOUNDATION_CONTRACTS: tuple[CsvContract, ...] = (
    CsvContract(
        name="swings",
        group="foundation",
        path=OUT_DIR / "swing_detection" / "swings.csv",
        description="Confirmed swing table from the retained swing detector.",
        required_columns=("start_date", "end_date", "direction", "amplitude_pct", "duration_days"),
        date_column=None,
    ),
    CsvContract(
        name="swing_sensitivity_summary",
        group="foundation",
        path=OUT_DIR / "swing_detection" / "swing_sensitivity_summary.csv",
        description="Swing detector sensitivity summary.",
        required_columns=("atr_window", "reversal_k", "swing_count"),
        date_column=None,
        allowed_missing=True,
    ),
    CsvContract(
        name="live_swing_state",
        group="foundation",
        path=OUT_DIR / "swing_bridge" / "live_swing_state.csv",
        description="Causal live swing-state surface.",
        required_columns=(
            "date",
            "live_swing_direction",
            "days_since_last_pivot",
            "distance_from_last_pivot_pct",
            "distance_from_last_pivot_atr_units",
            "last_confirmed_pivot_date",
            "last_confirmed_pivot_price",
            "current_swing_age_pct_of_median",
            "current_swing_size_pct_of_median",
            "swing_confirmed_today",
        ),
        forbidden_prefixes=("next_", "containing_", "buy_zone_", "sell_zone_", "dist_to_current_", "current_confirmed_"),
    ),
    CsvContract(
        name="swing_taxonomy",
        group="foundation",
        path=OUT_DIR / "swing_bridge" / "swing_taxonomy.csv",
        description="Confirmed swing taxonomy and classification table.",
        required_columns=(
            "swing_id",
            "start_date",
            "end_date",
            "direction",
            "abs_amplitude_pct",
            "size_class",
            "duration_class",
            "swing_granularity",
        ),
        date_column=None,
    ),
    CsvContract(
        name="swing_condition_mapping",
        group="foundation",
        path=OUT_DIR / "swing_bridge" / "swing_condition_mapping.csv",
        description="Condition-to-swing mapping table with explicit containing/next semantics.",
        required_columns=(
            "condition_name",
            "condition_family",
            "mapping_mode",
            "sample_count",
            "mapped_swing_rows",
            "swing_up_rate",
            "swing_down_rate",
        ),
        date_column=None,
        allowed_missing=True,
    ),
)


SIGNAL_STACK_CONTRACTS: tuple[CsvContract, ...] = (
    CsvContract(
        name="reversal_zone_dataset",
        group="signals",
        path=DEFAULT_REVERSAL_ZONE_DATASET_CSV_PATH,
        description="Daily reversal-zone feature/label surface.",
        required_columns=(
            "date",
            "close",
            "live_swing_direction",
            "current_confirmed_swing_id",
            "current_confirmed_swing_direction",
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ),
    ),
    CsvContract(
        name="swing_extreme_timing",
        group="signals",
        path=DEFAULT_SWING_EXTREME_TIMING_CSV_PATH,
        description="Combined buy/sell swing-extreme timing surface.",
        required_columns=(
            "date",
            "close",
            "buy_extreme_timing_score",
            "sell_extreme_timing_score",
            "buy_phase_prob",
            "sell_phase_prob",
            "buy_zone_within_5pct_above_low",
            "sell_zone_within_5pct_below_high",
        ),
    ),
    CsvContract(
        name="buy_side_hybrid",
        group="signals",
        path=DEFAULT_BUY_SIDE_HYBRID_SCORES_CSV_PATH,
        description="Promoted buy-side hybrid score surface.",
        required_columns=(
            "date",
            "close",
            "buy_fixed_extreme_timing_score",
            "buy_hybrid_weighted_balanced_score",
            "buy_hybrid_two_stage_score",
            "buy_zone_within_5pct_above_low",
            "buy_zone_within_3pct_above_low",
        ),
    ),
    CsvContract(
        name="swing_decision_layer",
        group="signals",
        path=DEFAULT_SWING_DECISION_LAYER_CSV_PATH,
        description="Daily combined buy/sell timing decision states.",
        required_columns=(
            "date",
            "close",
            "promoted_buy_timing_score",
            "promoted_sell_timing_score",
            "decision_state",
            "edge_clarity_score",
            "conflict_score",
        ),
    ),
    CsvContract(
        name="swing_playbook_layer",
        group="signals",
        path=DEFAULT_SWING_PLAYBOOK_LAYER_CSV_PATH,
        description="Human-readable playbook interpretation layer.",
        required_columns=(
            "date",
            "close",
            "decision_state",
            "playbook_label",
            "playbook_bias",
            "playbook_attention_level",
            "edge_clarity_score",
            "conflict_score",
        ),
    ),
    CsvContract(
        name="strategy_translation_layer",
        group="signals",
        path=DEFAULT_STRATEGY_TRANSLATION_CSV_PATH,
        description="Operational strategy-translation state layer.",
        required_columns=(
            "date",
            "close",
            "playbook_label",
            "operational_state",
            "operational_bias",
            "readiness_flag",
            "caution_flag",
            "invalidation_flag",
        ),
    ),
    CsvContract(
        name="rule_layer",
        group="signals",
        path=DEFAULT_RULE_LAYER_CSV_PATH,
        description="Permission/wait/block/invalidation rule layer.",
        required_columns=(
            "date",
            "close",
            "operational_state",
            "rule_state",
            "long_permission_flag",
            "sell_derisk_permission_flag",
            "confirmation_needed_flag",
            "block_action_flag",
            "invalidation_active_flag",
        ),
    ),
    CsvContract(
        name="signal_layer",
        group="signals",
        path=DEFAULT_SIGNAL_LAYER_CSV_PATH,
        description="Discrete structural signal realization layer.",
        required_columns=(
            "date",
            "close",
            "rule_state",
            "signal_state",
            "long_signal_event_flag",
            "sell_signal_event_flag",
            "signal_continuation_flag",
            "signal_invalidation_event_flag",
            "signal_active_flag",
        ),
    ),
)


ALL_CSV_CONTRACTS: tuple[CsvContract, ...] = (
    *FEATURE_SURFACE_CONTRACTS,
    *SWING_FOUNDATION_CONTRACTS,
    *SIGNAL_STACK_CONTRACTS,
)


def contracts_for_groups(groups: Iterable[str] | None = None) -> list[CsvContract]:
    selected = set(groups or ("features", "foundation", "signals"))
    return [contract for contract in ALL_CSV_CONTRACTS if contract.group in selected]


def _validate_date_column(frame: pd.DataFrame, contract: CsvContract) -> list[str]:
    if contract.date_column is None:
        return []
    if contract.date_column not in frame.columns:
        return [f"missing date column `{contract.date_column}`"]

    problems: list[str] = []
    parsed = pd.to_datetime(frame[contract.date_column], errors="coerce")
    if parsed.isna().any():
        problems.append(f"`{contract.date_column}` contains unparsable dates")
    if contract.require_unique_date and parsed.duplicated().any():
        problems.append(f"`{contract.date_column}` contains duplicate dates")
    if contract.require_sorted_date and not parsed.is_monotonic_increasing:
        problems.append(f"`{contract.date_column}` is not sorted ascending")
    return problems


def validate_csv_contract(contract: CsvContract, *, allow_missing: bool = False) -> ContractResult:
    if not contract.path.exists():
        if allow_missing or contract.allowed_missing:
            return ContractResult(
                name=contract.name,
                group=contract.group,
                status="SKIP",
                path=contract.path,
                message="missing optional/currently absent output",
            )
        return ContractResult(
            name=contract.name,
            group=contract.group,
            status="FAIL",
            path=contract.path,
            message="missing required output",
        )

    try:
        frame = pd.read_csv(contract.path)
    except Exception as exc:
        return ContractResult(
            name=contract.name,
            group=contract.group,
            status="FAIL",
            path=contract.path,
            message=f"could not read CSV: {exc}",
        )

    problems: list[str] = []
    if frame.empty:
        problems.append("CSV is empty")

    missing_columns = [column for column in contract.required_columns if column not in frame.columns]
    if missing_columns:
        problems.append(f"missing columns: {missing_columns}")

    forbidden_columns = [
        column
        for column in frame.columns
        if any(column.startswith(prefix) for prefix in contract.forbidden_prefixes)
    ]
    if forbidden_columns:
        problems.append(f"forbidden feature/label columns present: {forbidden_columns[:12]}")

    problems.extend(_validate_date_column(frame, contract))

    if problems:
        return ContractResult(
            name=contract.name,
            group=contract.group,
            status="FAIL",
            path=contract.path,
            message="; ".join(problems),
        )

    return ContractResult(
        name=contract.name,
        group=contract.group,
        status="PASS",
        path=contract.path,
        message=f"{len(frame)} rows, {len(frame.columns)} columns",
    )


def validate_csv_contracts(
    contracts: Iterable[CsvContract],
    *,
    allow_missing: bool = False,
) -> list[ContractResult]:
    return [validate_csv_contract(contract, allow_missing=allow_missing) for contract in contracts]


def validate_dashboard_contracts(*, allow_missing: bool = False) -> list[ContractResult]:
    results: list[ContractResult] = []
    for view_name, view in VIEW_REGISTRY.items():
        path = Path(view["path"])
        required_columns = {"date", "close"}
        for key in ("scores", "components", "labels", "diagnostics", "default_scores", "default_components", "default_labels"):
            required_columns.update(view.get(key, []))

        contract = CsvContract(
            name=f"dashboard:{view_name}",
            group="dashboard",
            path=path,
            description=f"Dashboard registered view `{view_name}`.",
            required_columns=tuple(sorted(required_columns)),
        )
        results.append(validate_csv_contract(contract, allow_missing=allow_missing))
    return results


def validate_groups(groups: Iterable[str], *, allow_missing: bool = False) -> list[ContractResult]:
    selected = set(groups)
    results: list[ContractResult] = []
    if selected & {"features", "foundation", "signals"}:
        results.extend(validate_csv_contracts(contracts_for_groups(selected), allow_missing=allow_missing))
    if "dashboard" in selected:
        results.extend(validate_dashboard_contracts(allow_missing=allow_missing))
    return results
