import type { FieldSchema } from '../../types/editor';
import type { EditorContext } from '../../types/editor';

const supportsSeriesAnnotations = (context: EditorContext): boolean => {
  return (
    context.currentChartType === 'line' ||
    context.currentChartType === 'bar' ||
    context.currentChartType === 'scatter' ||
    context.currentChartType === 'effectScatter' ||
    context.currentChartType === 'candlestick' ||
    context.currentChartType === 'radar'
  );
};

const createAnnotationLabelFields = ({
  keyPrefix,
  pathPrefix,
  labelPrefix,
  defaultPosition,
}: {
  keyPrefix: string;
  pathPrefix: string;
  labelPrefix: string;
  defaultPosition: string;
}): FieldSchema[] => {
  return [
    {
      key: `${keyPrefix}.label.show`,
      label: `${labelPrefix} Label Show`,
      path: `${pathPrefix}.label.show`,
      control: 'checkbox',
      defaultValue: true,
      group: labelPrefix,
      visibleWhen: supportsSeriesAnnotations,
      helpText: `Show ${labelPrefix.toLowerCase()} labels.`,
    },
    {
      key: `${keyPrefix}.label.position`,
      label: `${labelPrefix} Label Position`,
      path: `${pathPrefix}.label.position`,
      control: 'select',
      defaultValue: defaultPosition,
      complexity: 'advanced',
      group: labelPrefix,
      visibleWhen: supportsSeriesAnnotations,
      helpText: `Place ${labelPrefix.toLowerCase()} labels around annotation graphics.`,
      options: [
        { label: 'Start', value: 'start' },
        { label: 'Middle', value: 'middle' },
        { label: 'End', value: 'end' },
        { label: 'Top', value: 'top' },
        { label: 'Bottom', value: 'bottom' },
        { label: 'Left', value: 'left' },
        { label: 'Right', value: 'right' },
        { label: 'Inside', value: 'inside' },
      ],
    },
    {
      key: `${keyPrefix}.label.formatter`,
      label: `${labelPrefix} Label Formatter`,
      path: `${pathPrefix}.label.formatter`,
      control: 'textarea',
      textareaMode: 'plain',
      defaultValue: '',
      placeholder: '{b}: {c}',
      complexity: 'advanced',
      group: labelPrefix,
      visibleWhen: supportsSeriesAnnotations,
      helpText: `Optional formatter text for ${labelPrefix.toLowerCase()} labels.`,
    },
  ];
};

export const seriesAnnotationFields: FieldSchema[] = [
  {
    key: 'series.markLine.show',
    label: 'MarkLine Show',
    path: 'series.$seriesIndex.markLine.show',
    control: 'checkbox',
    defaultValue: false,
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Show markLine annotations for this series.',
  },
  {
    key: 'series.markLine.silent',
    label: 'MarkLine Silent',
    path: 'series.$seriesIndex.markLine.silent',
    control: 'checkbox',
    defaultValue: false,
    complexity: 'advanced',
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Disable hover/click interactions on mark lines.',
  },
  {
    key: 'series.markLine.symbol',
    label: 'MarkLine Symbol',
    path: 'series.$seriesIndex.markLine.symbol',
    control: 'text',
    defaultValue: 'none',
    complexity: 'advanced',
    placeholder: 'none / arrow / circle',
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Symbol used for mark line ends.',
  },
  {
    key: 'series.markLine.precision',
    label: 'MarkLine Precision',
    path: 'series.$seriesIndex.markLine.precision',
    control: 'number',
    defaultValue: 2,
    complexity: 'advanced',
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Decimal precision for mark line value labels.',
  },
  ...createAnnotationLabelFields({
    keyPrefix: 'series.markLine',
    pathPrefix: 'series.$seriesIndex.markLine',
    labelPrefix: 'MarkLine',
    defaultPosition: 'end',
  }),
  {
    key: 'series.markLine.lineStyle.color',
    label: 'MarkLine Line Color',
    path: 'series.$seriesIndex.markLine.lineStyle.color',
    control: 'text',
    defaultValue: '#f59e0b',
    complexity: 'advanced',
    placeholder: '#f59e0b / rgba(...)',
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Stroke color for mark lines.',
  },
  {
    key: 'series.markLine.lineStyle.width',
    label: 'MarkLine Line Width',
    path: 'series.$seriesIndex.markLine.lineStyle.width',
    control: 'number',
    defaultValue: 2,
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Stroke width for mark lines.',
  },
  {
    key: 'series.markLine.lineStyle.type',
    label: 'MarkLine Line Type',
    path: 'series.$seriesIndex.markLine.lineStyle.type',
    control: 'select',
    defaultValue: 'solid',
    complexity: 'advanced',
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Dash style for mark lines.',
    options: [
      { label: 'Solid', value: 'solid' },
      { label: 'Dashed', value: 'dashed' },
      { label: 'Dotted', value: 'dotted' },
    ],
  },
  {
    key: 'series.markLine.data',
    label: 'MarkLine Data (JSON)',
    path: 'series.$seriesIndex.markLine.data',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: [],
    placeholder: '[{ "yAxis": 120 }]',
    complexity: 'advanced',
    group: 'MarkLine',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'MarkLine item array as JSON.',
  },
  {
    key: 'series.markPoint.symbol',
    label: 'MarkPoint Symbol',
    path: 'series.$seriesIndex.markPoint.symbol',
    control: 'select',
    defaultValue: 'pin',
    group: 'MarkPoint',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Marker symbol for mark points.',
    options: [
      { label: 'Pin', value: 'pin' },
      { label: 'Circle', value: 'circle' },
      { label: 'Rect', value: 'rect' },
      { label: 'Triangle', value: 'triangle' },
      { label: 'Diamond', value: 'diamond' },
      { label: 'Arrow', value: 'arrow' },
    ],
  },
  {
    key: 'series.markPoint.symbolSize',
    label: 'MarkPoint Symbol Size',
    path: 'series.$seriesIndex.markPoint.symbolSize',
    control: 'number',
    defaultValue: 50,
    complexity: 'advanced',
    group: 'MarkPoint',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Size for mark point symbols.',
  },
  ...createAnnotationLabelFields({
    keyPrefix: 'series.markPoint',
    pathPrefix: 'series.$seriesIndex.markPoint',
    labelPrefix: 'MarkPoint',
    defaultPosition: 'top',
  }),
  {
    key: 'series.markPoint.itemStyle.color',
    label: 'MarkPoint Color',
    path: 'series.$seriesIndex.markPoint.itemStyle.color',
    control: 'text',
    defaultValue: '#ef4444',
    complexity: 'advanced',
    group: 'MarkPoint',
    visibleWhen: supportsSeriesAnnotations,
    placeholder: '#ef4444 / rgba(...)',
    helpText: 'Fill color for mark point symbols.',
  },
  {
    key: 'series.markPoint.data',
    label: 'MarkPoint Data (JSON)',
    path: 'series.$seriesIndex.markPoint.data',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: [],
    placeholder: '[{ "type": "max", "name": "Max" }]',
    complexity: 'advanced',
    group: 'MarkPoint',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'MarkPoint item array as JSON.',
  },
  {
    key: 'series.markArea.silent',
    label: 'MarkArea Silent',
    path: 'series.$seriesIndex.markArea.silent',
    control: 'checkbox',
    defaultValue: false,
    complexity: 'advanced',
    group: 'MarkArea',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Disable hover/click interactions on marked ranges.',
  },
  ...createAnnotationLabelFields({
    keyPrefix: 'series.markArea',
    pathPrefix: 'series.$seriesIndex.markArea',
    labelPrefix: 'MarkArea',
    defaultPosition: 'inside',
  }),
  {
    key: 'series.markArea.itemStyle.color',
    label: 'MarkArea Color',
    path: 'series.$seriesIndex.markArea.itemStyle.color',
    control: 'text',
    defaultValue: 'rgba(59, 130, 246, 0.2)',
    complexity: 'advanced',
    group: 'MarkArea',
    visibleWhen: supportsSeriesAnnotations,
    placeholder: '#3b82f6 / rgba(...)',
    helpText: 'Fill color for marked ranges.',
  },
  {
    key: 'series.markArea.itemStyle.opacity',
    label: 'MarkArea Opacity',
    path: 'series.$seriesIndex.markArea.itemStyle.opacity',
    control: 'number',
    defaultValue: 0.2,
    complexity: 'advanced',
    group: 'MarkArea',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'Opacity for marked range fill (0 to 1).',
  },
  {
    key: 'series.markArea.data',
    label: 'MarkArea Data (JSON)',
    path: 'series.$seriesIndex.markArea.data',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: [],
    placeholder: '[[{ "xAxis": "Jan" }, { "xAxis": "Mar" }]]',
    complexity: 'advanced',
    group: 'MarkArea',
    visibleWhen: supportsSeriesAnnotations,
    helpText: 'MarkArea range item array as JSON.',
  },
];
