import type { FieldSchema } from '../../types/editor';
import { isBarSeries } from '../helpers/fieldBuilders';

export const barSeriesFields: FieldSchema[] = [
  {
    key: 'series.coordinateSystem.bar',
    label: 'Coordinate System',
    path: 'series.$seriesIndex.coordinateSystem',
    control: 'select',
    defaultValue: 'cartesian2d',
    visibleWhen: isBarSeries,
    complexity: 'advanced',
    helpText: 'Use cartesian2d for standard bars or polar for radial bars.',
    options: [
      { label: 'Cartesian 2D', value: 'cartesian2d' },
      { label: 'Polar', value: 'polar' },
    ],
  },
  {
    key: 'series.barWidth',
    label: 'Bar Width',
    path: 'series.$seriesIndex.barWidth',
    control: 'text',
    defaultValue: '40%',
    placeholder: '40% or 24',
    visibleWhen: isBarSeries,
    helpText: 'Control bar width.',
  },
  {
    key: 'series.barGap',
    label: 'Bar Gap',
    path: 'series.$seriesIndex.barGap',
    control: 'text',
    defaultValue: '30%',
    visibleWhen: isBarSeries,
    helpText: 'Spacing between bars of adjacent series.',
  },
  {
    key: 'series.stack',
    label: 'Stack',
    path: 'series.$seriesIndex.stack',
    control: 'text',
    defaultValue: '',
    placeholder: 'stack-group-1',
    visibleWhen: isBarSeries,
    helpText: 'Use same stack key to stack bars together.',
  },
  {
    key: 'series.showBackground',
    label: 'Show Background',
    path: 'series.$seriesIndex.showBackground',
    control: 'checkbox',
    defaultValue: false,
    visibleWhen: isBarSeries,
    helpText: 'Draw background bars behind values.',
  },
  {
    key: 'series.backgroundStyle.color',
    label: 'Background Color',
    path: 'series.$seriesIndex.backgroundStyle.color',
    control: 'text',
    defaultValue: 'rgba(180,180,180,0.2)',
    visibleWhen: isBarSeries,
    helpText: 'Background bar color.',
  },
];
