import type { FieldSchema } from '../../types/editor';
import { isCandlestickSeries } from '../helpers/fieldBuilders';

export const candlestickSeriesFields: FieldSchema[] = [
  {
    key: 'series.encode.x.candlestick',
    label: 'Encode X (Candlestick)',
    path: 'series.$seriesIndex.encode.x',
    control: 'text',
    defaultValue: '0',
    group: 'Candlestick Mapping',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    placeholder: '0 / Date',
    helpText: 'Dimension mapped to candlestick category/date axis.',
  },
  {
    key: 'series.encode.y.candlestick',
    label: 'Encode OHLC (Y)',
    path: 'series.$seriesIndex.encode.y',
    control: 'textarea',
    valueEditor: 'string-array',
    defaultValue: ['1', '2', '3', '4'],
    group: 'Candlestick Mapping',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Use Open, Close, Low, High order for V1 (one dimension per line).',
  },
  {
    key: 'series.itemStyle.color.candlestick',
    label: 'Up Color',
    path: 'series.$seriesIndex.itemStyle.color',
    control: 'text',
    defaultValue: '#26a69a',
    group: 'Candlestick Style',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Color when close >= open.',
  },
  {
    key: 'series.itemStyle.color0.candlestick',
    label: 'Down Color',
    path: 'series.$seriesIndex.itemStyle.color0',
    control: 'text',
    defaultValue: '#ef5350',
    group: 'Candlestick Style',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Color when close < open.',
  },
  {
    key: 'series.itemStyle.borderColor.candlestick',
    label: 'Up Border Color',
    path: 'series.$seriesIndex.itemStyle.borderColor',
    control: 'text',
    defaultValue: '#26a69a',
    group: 'Candlestick Style',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Border color for up candles.',
  },
  {
    key: 'series.itemStyle.borderColor0.candlestick',
    label: 'Down Border Color',
    path: 'series.$seriesIndex.itemStyle.borderColor0',
    control: 'text',
    defaultValue: '#ef5350',
    group: 'Candlestick Style',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Border color for down candles.',
  },
  {
    key: 'series.barWidth.candlestick',
    label: 'Bar Width',
    path: 'series.$seriesIndex.barWidth',
    control: 'text',
    defaultValue: '60%',
    group: 'Candlestick Performance',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Width of each candlestick body.',
  },
  {
    key: 'series.large.candlestick',
    label: 'Large Mode',
    path: 'series.$seriesIndex.large',
    control: 'checkbox',
    defaultValue: false,
    group: 'Candlestick Performance',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Enable large rendering mode for high-volume points.',
  },
  {
    key: 'series.largeThreshold.candlestick',
    label: 'Large Threshold',
    path: 'series.$seriesIndex.largeThreshold',
    control: 'number',
    defaultValue: 600,
    group: 'Candlestick Performance',
    complexity: 'advanced',
    visibleWhen: isCandlestickSeries,
    helpText: 'Data count threshold to switch into large mode.',
  },
];
