import type { FieldSchema } from '../../types/editor';
import {
  createAreaStyleFields,
  createLabelFields,
  createLineStyleFields,
  createSeriesInteractionStateFields,
  createSeriesItemStyleFields,
  createSeriesRenderAnimationFields,
  supportsCommonSeriesAreaStyle,
  supportsCommonSeriesInteractionStates,
  supportsCommonSeriesItemStyle,
  supportsCommonSeriesLineStyle,
} from '../helpers/fieldBuilders';

export const seriesCommonFields: FieldSchema[] = [
  {
    key: 'series.name',
    label: 'Name',
    path: 'series.$seriesIndex.name',
    control: 'text',
    defaultValue: 'Series',
    helpText: 'Name used in legend and tooltips.',
  },
  {
    key: 'series.type',
    label: 'Type',
    path: 'series.$seriesIndex.type',
    control: 'select',
    defaultValue: 'line',
    helpText: 'Select series renderer.',
    options: [
      { label: 'Line', value: 'line' },
      { label: 'Bar', value: 'bar' },
      { label: 'Pie', value: 'pie' },
      { label: 'Candlestick', value: 'candlestick' },
      { label: 'Scatter', value: 'scatter' },
      { label: 'Effect Scatter', value: 'effectScatter' },
      { label: 'Radar', value: 'radar' },
      { label: 'Heatmap', value: 'heatmap' },
      { label: 'Funnel', value: 'funnel' },
      { label: 'Gauge', value: 'gauge' },
      { label: 'Parallel', value: 'parallel' },
      { label: 'Map', value: 'map' },
    ],
  },
  {
    key: 'series.color',
    label: 'Color',
    path: 'series.$seriesIndex.color',
    control: 'text',
    defaultValue: '',
    placeholder: '#3b82f6 / rgba(...)',
    helpText: 'Override automatic series color.',
  },
  ...createLabelFields({
    keyPrefix: 'series.label',
    pathPrefix: 'series.$seriesIndex.label',
    defaultShow: false,
    defaultPosition: 'top',
    defaultFormatter: '',
    defaultColor: '',
    defaultFontSize: 12,
    defaultDistance: 5,
  }),
  ...createSeriesItemStyleFields({
    keyPrefix: 'series.itemStyle',
    pathPrefix: 'series.$seriesIndex.itemStyle',
    visibleWhen: supportsCommonSeriesItemStyle,
    defaultColor: '',
    defaultOpacity: 1,
    defaultBorderColor: '#ffffff',
    defaultBorderWidth: 0,
    defaultBorderType: 'solid',
    defaultBorderRadius: 0,
  }),
  ...createLineStyleFields({
    keyPrefix: 'series.lineStyle.common',
    pathPrefix: 'series.$seriesIndex.lineStyle',
    visibleWhen: supportsCommonSeriesLineStyle,
    defaultColor: '',
    defaultWidth: 2,
    defaultType: 'solid',
    defaultOpacity: 1,
  }),
  ...createAreaStyleFields({
    keyPrefix: 'series.areaStyle.common',
    pathPrefix: 'series.$seriesIndex.areaStyle',
    visibleWhen: supportsCommonSeriesAreaStyle,
    defaultColor: '',
    defaultOpacity: 0.15,
  }),
  ...createSeriesInteractionStateFields({
    keyPrefix: 'series.state',
    pathPrefix: 'series.$seriesIndex',
    visibleWhen: supportsCommonSeriesInteractionStates,
    defaultEmphasisDisabled: false,
    defaultEmphasisFocus: 'none',
    defaultEmphasisScale: true,
    defaultBlurItemStyleOpacity: 0.3,
    defaultSelectDisabled: false,
  }),
  ...createSeriesRenderAnimationFields({
    keyPrefix: 'series.render',
    pathPrefix: 'series.$seriesIndex',
    defaultZ: 2,
    defaultZLevel: 0,
    defaultAnimation: true,
    defaultAnimationDuration: 1000,
    defaultAnimationEasing: 'cubicOut',
  }),
  {
    key: 'series.data',
    label: 'Data (JSON)',
    path: 'series.$seriesIndex.data',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: [120, 200, 150],
    placeholder: '[120, 200, 150] or [{"value":120,"name":"A"}]',
    helpText: 'Manual data override for the selected series.',
  },
];
