import type { FieldSchema } from '../../types/editor';
import { isEffectScatterSeries } from '../helpers/fieldBuilders';

export const effectScatterSeriesFields: FieldSchema[] = [
  {
    key: 'series.coordinateSystem.effectScatter',
    label: 'Coordinate System (Effect Scatter)',
    path: 'series.$seriesIndex.coordinateSystem',
    control: 'select',
    defaultValue: 'cartesian2d',
    visibleWhen: isEffectScatterSeries,
    group: 'Effect Scatter Mapping',
    helpText: 'Choose coordinate system for effect scatter points.',
    options: [
      { label: 'Cartesian 2D', value: 'cartesian2d' },
      { label: 'Geo', value: 'geo' },
      { label: 'Polar', value: 'polar' },
      { label: 'Calendar', value: 'calendar' },
      { label: 'Single Axis', value: 'singleAxis' },
    ],
  },
  {
    key: 'series.symbol.effectScatter',
    label: 'Symbol',
    path: 'series.$seriesIndex.symbol',
    control: 'select',
    defaultValue: 'circle',
    visibleWhen: isEffectScatterSeries,
    group: 'Effect Scatter Style',
    helpText: 'Marker symbol shape.',
    options: [
      { label: 'Circle', value: 'circle' },
      { label: 'Rect', value: 'rect' },
      { label: 'Round Rect', value: 'roundRect' },
      { label: 'Triangle', value: 'triangle' },
      { label: 'Diamond', value: 'diamond' },
      { label: 'Pin', value: 'pin' },
      { label: 'Arrow', value: 'arrow' },
      { label: 'None', value: 'none' },
    ],
  },
  {
    key: 'series.symbolSize.effectScatter',
    label: 'Symbol Size',
    path: 'series.$seriesIndex.symbolSize',
    control: 'number',
    defaultValue: 14,
    visibleWhen: isEffectScatterSeries,
    group: 'Effect Scatter Style',
    helpText: 'Marker size in pixels.',
  },
  {
    key: 'series.itemStyle.color.effectScatter',
    label: 'Point Color',
    path: 'series.$seriesIndex.itemStyle.color',
    control: 'text',
    defaultValue: '#16a34a',
    visibleWhen: isEffectScatterSeries,
    group: 'Effect Scatter Style',
    helpText: 'Color for effect scatter points.',
  },
  {
    key: 'series.itemStyle.opacity.effectScatter',
    label: 'Point Opacity',
    path: 'series.$seriesIndex.itemStyle.opacity',
    control: 'number',
    defaultValue: 0.9,
    visibleWhen: isEffectScatterSeries,
    group: 'Effect Scatter Style',
    helpText: 'Opacity for effect scatter points (0 to 1).',
  },
  {
    key: 'series.label.show.effectScatter',
    label: 'Label Show',
    path: 'series.$seriesIndex.label.show',
    control: 'checkbox',
    defaultValue: false,
    visibleWhen: isEffectScatterSeries,
    group: 'Effect Scatter Style',
    helpText: 'Show labels for points.',
  },
  {
    key: 'series.rippleEffect.scale',
    label: 'Ripple Scale',
    path: 'series.$seriesIndex.rippleEffect.scale',
    control: 'number',
    defaultValue: 2.5,
    visibleWhen: isEffectScatterSeries,
    group: 'Ripple Effect',
    complexity: 'advanced',
    helpText: 'Scale factor of ripple animation.',
  },
  {
    key: 'series.rippleEffect.brushType',
    label: 'Ripple Brush Type',
    path: 'series.$seriesIndex.rippleEffect.brushType',
    control: 'select',
    defaultValue: 'stroke',
    visibleWhen: isEffectScatterSeries,
    group: 'Ripple Effect',
    complexity: 'advanced',
    helpText: 'Rendering style for ripple circles.',
    options: [
      { label: 'Stroke', value: 'stroke' },
      { label: 'Fill', value: 'fill' },
    ],
  },
  {
    key: 'series.rippleEffect.json',
    label: 'Ripple Effect (JSON)',
    path: 'series.$seriesIndex.rippleEffect',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: { scale: 2.5, brushType: 'stroke' },
    visibleWhen: isEffectScatterSeries,
    group: 'Ripple Effect',
    complexity: 'expert',
    helpText: 'Advanced ripple effect configuration as JSON fallback.',
  },
];
