import type { FieldSchema } from '../../types/editor';
import { supportsCommonEncode } from '../helpers/fieldBuilders';

export const seriesEncodeFields: FieldSchema[] = [
  {
    key: 'series.encode.x',
    label: 'Encode X',
    path: 'series.$seriesIndex.encode.x',
    control: 'text',
    defaultValue: '',
    group: 'Encode',
    complexity: 'advanced',
    visibleWhen: supportsCommonEncode,
    placeholder: 'category / 0',
    helpText: 'Map dataset dimension to x-axis role.',
  },
  {
    key: 'series.encode.y',
    label: 'Encode Y',
    path: 'series.$seriesIndex.encode.y',
    control: 'text',
    defaultValue: '',
    group: 'Encode',
    complexity: 'advanced',
    visibleWhen: supportsCommonEncode,
    placeholder: 'value / 1',
    helpText: 'Map dataset dimension to y-axis role.',
  },
  {
    key: 'series.encode.tooltip',
    label: 'Encode Tooltip',
    path: 'series.$seriesIndex.encode.tooltip',
    control: 'textarea',
    valueEditor: 'string-array',
    defaultValue: [],
    group: 'Encode',
    complexity: 'advanced',
    visibleWhen: supportsCommonEncode,
    helpText: 'Dimensions included in tooltip (one per line).',
  },
  {
    key: 'series.encode.itemName',
    label: 'Encode Item Name',
    path: 'series.$seriesIndex.encode.itemName',
    control: 'text',
    defaultValue: '',
    group: 'Encode',
    complexity: 'advanced',
    visibleWhen: supportsCommonEncode,
    placeholder: 'name / 0',
    helpText: 'Dimension used as the item name/category.',
  },
  {
    key: 'series.encode.seriesName',
    label: 'Encode Series Name',
    path: 'series.$seriesIndex.encode.seriesName',
    control: 'text',
    defaultValue: '',
    group: 'Encode',
    complexity: 'advanced',
    visibleWhen: supportsCommonEncode,
    placeholder: 'series / 2',
    helpText: 'Dimension used to derive series name.',
  },
  {
    key: 'series.encode.value',
    label: 'Encode Value',
    path: 'series.$seriesIndex.encode.value',
    control: 'textarea',
    valueEditor: 'string-array',
    defaultValue: [],
    group: 'Encode',
    complexity: 'advanced',
    visibleWhen: supportsCommonEncode,
    helpText: 'Dimensions used as value channels (one per line).',
  },
];
