import type { FieldSchema } from '../../types/editor';
import { isFunnelSeries } from '../helpers/fieldBuilders';

export const funnelSeriesFields: FieldSchema[] = [
  {
    key: 'series.sort.funnel',
    label: 'Sort',
    path: 'series.$seriesIndex.sort',
    control: 'select',
    defaultValue: 'descending',
    visibleWhen: isFunnelSeries,
    group: 'Funnel Layout',
    helpText: 'Order of funnel stages.',
    options: [
      { label: 'Descending', value: 'descending' },
      { label: 'Ascending', value: 'ascending' },
      { label: 'None', value: 'none' },
    ],
  },
  {
    key: 'series.min.funnel',
    label: 'Min',
    path: 'series.$seriesIndex.min',
    control: 'number',
    defaultValue: 0,
    visibleWhen: isFunnelSeries,
    group: 'Funnel Layout',
    complexity: 'advanced',
    helpText: 'Minimum data value bound used for sizing.',
  },
  {
    key: 'series.max.funnel',
    label: 'Max',
    path: 'series.$seriesIndex.max',
    control: 'number',
    defaultValue: 100,
    visibleWhen: isFunnelSeries,
    group: 'Funnel Layout',
    complexity: 'advanced',
    helpText: 'Maximum data value bound used for sizing.',
  },
  {
    key: 'series.minSize.funnel',
    label: 'Min Size',
    path: 'series.$seriesIndex.minSize',
    control: 'text',
    defaultValue: '0%',
    visibleWhen: isFunnelSeries,
    group: 'Funnel Layout',
    complexity: 'advanced',
    helpText: 'Minimum segment size (percent or number).',
  },
  {
    key: 'series.maxSize.funnel',
    label: 'Max Size',
    path: 'series.$seriesIndex.maxSize',
    control: 'text',
    defaultValue: '100%',
    visibleWhen: isFunnelSeries,
    group: 'Funnel Layout',
    complexity: 'advanced',
    helpText: 'Maximum segment size (percent or number).',
  },
  {
    key: 'series.gap.funnel',
    label: 'Gap',
    path: 'series.$seriesIndex.gap',
    control: 'number',
    defaultValue: 2,
    visibleWhen: isFunnelSeries,
    group: 'Funnel Layout',
    complexity: 'advanced',
    helpText: 'Gap between funnel segments in pixels.',
  },
  {
    key: 'series.label.show.funnel',
    label: 'Label Show (Funnel)',
    path: 'series.$seriesIndex.label.show',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isFunnelSeries,
    group: 'Funnel Label',
    helpText: 'Show labels on funnel segments.',
  },
  {
    key: 'series.label.position.funnel',
    label: 'Label Position (Funnel)',
    path: 'series.$seriesIndex.label.position',
    control: 'select',
    defaultValue: 'inside',
    visibleWhen: isFunnelSeries,
    group: 'Funnel Label',
    complexity: 'advanced',
    helpText: 'Where to place funnel labels.',
    options: [
      { label: 'Inside', value: 'inside' },
      { label: 'Left', value: 'left' },
      { label: 'Right', value: 'right' },
      { label: 'Outside', value: 'outside' },
    ],
  },
  {
    key: 'series.label.formatter.funnel',
    label: 'Label Formatter (Funnel)',
    path: 'series.$seriesIndex.label.formatter',
    control: 'textarea',
    textareaMode: 'plain',
    defaultValue: '{b}: {c}',
    visibleWhen: isFunnelSeries,
    group: 'Funnel Label',
    complexity: 'advanced',
    helpText: 'Pattern used to render funnel labels.',
  },
  {
    key: 'series.labelLine.show.funnel',
    label: 'Label Line Show',
    path: 'series.$seriesIndex.labelLine.show',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isFunnelSeries,
    group: 'Funnel Label',
    complexity: 'advanced',
    helpText: 'Show label guide lines for outside labels.',
  },
  {
    key: 'series.labelLine.length.funnel',
    label: 'Label Line Length',
    path: 'series.$seriesIndex.labelLine.length',
    control: 'number',
    defaultValue: 12,
    visibleWhen: isFunnelSeries,
    group: 'Funnel Label',
    complexity: 'advanced',
    helpText: 'Length of funnel label lines.',
  },
];
