import type { FieldSchema } from '../../types/editor';
import { isGaugeSeries } from '../helpers/fieldBuilders';

export const gaugeSeriesFields: FieldSchema[] = [
  {
    key: 'series.min.gauge',
    label: 'Min',
    path: 'series.$seriesIndex.min',
    control: 'number',
    defaultValue: 0,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Scale',
    helpText: 'Minimum gauge value.',
  },
  {
    key: 'series.max.gauge',
    label: 'Max',
    path: 'series.$seriesIndex.max',
    control: 'number',
    defaultValue: 100,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Scale',
    helpText: 'Maximum gauge value.',
  },
  {
    key: 'series.splitNumber.gauge',
    label: 'Split Number',
    path: 'series.$seriesIndex.splitNumber',
    control: 'number',
    defaultValue: 10,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Scale',
    complexity: 'advanced',
    helpText: 'Number of segments between min and max.',
  },
  {
    key: 'series.startAngle.gauge',
    label: 'Start Angle',
    path: 'series.$seriesIndex.startAngle',
    control: 'number',
    defaultValue: 225,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Arc',
    complexity: 'advanced',
    helpText: 'Start angle in degrees.',
  },
  {
    key: 'series.endAngle.gauge',
    label: 'End Angle',
    path: 'series.$seriesIndex.endAngle',
    control: 'number',
    defaultValue: -45,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Arc',
    complexity: 'advanced',
    helpText: 'End angle in degrees.',
  },
  {
    key: 'series.progress.show.gauge',
    label: 'Progress Show',
    path: 'series.$seriesIndex.progress.show',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Arc',
    complexity: 'advanced',
    helpText: 'Show progress arc fill.',
  },
  {
    key: 'series.pointer.show.gauge',
    label: 'Pointer Show',
    path: 'series.$seriesIndex.pointer.show',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Arc',
    complexity: 'advanced',
    helpText: 'Show gauge pointer needle.',
  },
  {
    key: 'series.axisLine.width.gauge',
    label: 'Axis Line Width',
    path: 'series.$seriesIndex.axisLine.lineStyle.width',
    control: 'number',
    defaultValue: 12,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Arc',
    complexity: 'advanced',
    helpText: 'Thickness of gauge axis arc.',
  },
  {
    key: 'series.detail.show.gauge',
    label: 'Detail Show',
    path: 'series.$seriesIndex.detail.show',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Detail',
    helpText: 'Show central value detail text.',
  },
  {
    key: 'series.detail.formatter.gauge',
    label: 'Detail Formatter',
    path: 'series.$seriesIndex.detail.formatter',
    control: 'text',
    defaultValue: '{value}',
    visibleWhen: isGaugeSeries,
    group: 'Gauge Detail',
    complexity: 'advanced',
    helpText: 'Formatter for gauge detail text.',
  },
  {
    key: 'series.detail.offsetCenter.gauge',
    label: 'Detail Offset Center',
    path: 'series.$seriesIndex.detail.offsetCenter',
    control: 'text',
    valueEditor: 'tuple',
    tupleLabels: ['Offset X', 'Offset Y'],
    defaultValue: ['0%', '60%'],
    visibleWhen: isGaugeSeries,
    group: 'Gauge Detail',
    complexity: 'advanced',
    helpText: 'Offset for detail text from center.',
  },
  {
    key: 'series.title.show.gauge',
    label: 'Title Show (Gauge)',
    path: 'series.$seriesIndex.title.show',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isGaugeSeries,
    group: 'Gauge Title',
    complexity: 'advanced',
    helpText: 'Show gauge title text near the detail value.',
  },
  {
    key: 'series.title.offsetCenter.gauge',
    label: 'Title Offset Center',
    path: 'series.$seriesIndex.title.offsetCenter',
    control: 'text',
    valueEditor: 'tuple',
    tupleLabels: ['Offset X', 'Offset Y'],
    defaultValue: ['0%', '85%'],
    visibleWhen: isGaugeSeries,
    group: 'Gauge Title',
    complexity: 'advanced',
    helpText: 'Offset for gauge title text from center.',
  },
];
