import type { FieldSchema } from '../../types/editor';
import { isHeatmapSeries } from '../helpers/fieldBuilders';

export const heatmapSeriesFields: FieldSchema[] = [
  {
    key: 'series.coordinateSystem.heatmap',
    label: 'Coordinate System',
    path: 'series.$seriesIndex.coordinateSystem',
    control: 'select',
    defaultValue: 'cartesian2d',
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Basic',
    helpText: 'Cartesian2d works with xAxis/yAxis category heatmaps.',
    options: [
      { label: 'Cartesian 2D', value: 'cartesian2d' },
      { label: 'Calendar', value: 'calendar' },
      { label: 'Geo', value: 'geo' },
    ],
  },
  {
    key: 'series.encode.x.heatmap',
    label: 'Encode X',
    path: 'series.$seriesIndex.encode.x',
    control: 'text',
    defaultValue: '0',
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Mapping',
    complexity: 'advanced',
    placeholder: '0 / xCategory',
    helpText: 'Dimension index/name used for X categories.',
  },
  {
    key: 'series.encode.y.heatmap',
    label: 'Encode Y',
    path: 'series.$seriesIndex.encode.y',
    control: 'text',
    defaultValue: '1',
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Mapping',
    complexity: 'advanced',
    placeholder: '1 / yCategory',
    helpText: 'Dimension index/name used for Y categories.',
  },
  {
    key: 'series.encode.value.heatmap',
    label: 'Encode Value',
    path: 'series.$seriesIndex.encode.value',
    control: 'textarea',
    valueEditor: 'string-array',
    defaultValue: ['2'],
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Mapping',
    complexity: 'advanced',
    helpText: 'Value dimension(s) used for intensity (one per line).',
  },
  {
    key: 'series.label.show.heatmap',
    label: 'Label Show (Heatmap)',
    path: 'series.$seriesIndex.label.show',
    control: 'checkbox',
    defaultValue: false,
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Style',
    helpText: 'Show value labels inside heatmap cells.',
  },
  {
    key: 'series.itemStyle.borderColor.heatmap',
    label: 'Cell Border Color',
    path: 'series.$seriesIndex.itemStyle.borderColor',
    control: 'text',
    defaultValue: '#ffffff',
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Style',
    complexity: 'advanced',
    helpText: 'Border color for each heatmap cell.',
  },
  {
    key: 'series.itemStyle.borderWidth.heatmap',
    label: 'Cell Border Width',
    path: 'series.$seriesIndex.itemStyle.borderWidth',
    control: 'number',
    defaultValue: 1,
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Style',
    complexity: 'advanced',
    helpText: 'Border width for each heatmap cell.',
  },
  {
    key: 'series.progressive.heatmap',
    label: 'Progressive',
    path: 'series.$seriesIndex.progressive',
    control: 'number',
    defaultValue: 0,
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Performance',
    complexity: 'expert',
    helpText: 'Progressive rendering chunk size for large heatmaps (0 disables).',
  },
  {
    key: 'series.blurSize.heatmap',
    label: 'Blur Size',
    path: 'series.$seriesIndex.blurSize',
    control: 'number',
    defaultValue: 20,
    visibleWhen: isHeatmapSeries,
    group: 'Heatmap Performance',
    complexity: 'expert',
    helpText: 'Blur size for visual smoothing in large heatmaps.',
  },
];
