import type { FieldSchema } from '../../types/editor';
import { isMapSeries } from '../helpers/fieldBuilders';

export const mapSeriesFields: FieldSchema[] = [
  {
    key: 'series.map.name',
    label: 'Map Name',
    path: 'series.$seriesIndex.map',
    control: 'text',
    defaultValue: 'world-lite',
    visibleWhen: isMapSeries,
    group: 'Map',
    helpText: 'Name of a registered map source. V1 includes world-lite by default.',
    placeholder: 'world-lite',
  },
  {
    key: 'series.map.roam',
    label: 'Roam',
    path: 'series.$seriesIndex.roam',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isMapSeries,
    group: 'Map',
    helpText: 'Allow panning and zooming.',
  },
  {
    key: 'series.map.zoom',
    label: 'Zoom',
    path: 'series.$seriesIndex.zoom',
    control: 'number',
    defaultValue: 1,
    visibleWhen: isMapSeries,
    group: 'Map',
    complexity: 'advanced',
    helpText: 'Initial zoom level for map series.',
  },
  {
    key: 'series.map.label.show',
    label: 'Label Show',
    path: 'series.$seriesIndex.label.show',
    control: 'checkbox',
    defaultValue: false,
    visibleWhen: isMapSeries,
    group: 'Map',
    complexity: 'advanced',
    helpText: 'Show region labels.',
  },
  {
    key: 'series.map.itemStyle.areaColor',
    label: 'Area Color',
    path: 'series.$seriesIndex.itemStyle.areaColor',
    control: 'text',
    defaultValue: '#dbeafe',
    visibleWhen: isMapSeries,
    group: 'Map',
    complexity: 'advanced',
    helpText: 'Default fill color for regions.',
  },
  {
    key: 'series.map.itemStyle.borderColor',
    label: 'Border Color',
    path: 'series.$seriesIndex.itemStyle.borderColor',
    control: 'text',
    defaultValue: '#64748b',
    visibleWhen: isMapSeries,
    group: 'Map',
    complexity: 'advanced',
    helpText: 'Border color for regions.',
  },
];
