import type { FieldSchema } from '../../types/editor';
import { isParallelSeries } from '../helpers/fieldBuilders';

export const parallelSeriesFields: FieldSchema[] = [
  {
    key: 'series.smooth.parallel',
    label: 'Smooth',
    path: 'series.$seriesIndex.smooth',
    control: 'checkbox',
    defaultValue: false,
    visibleWhen: isParallelSeries,
    group: 'Parallel Style',
    helpText: 'Smooth lines in parallel coordinates.',
  },
  {
    key: 'series.progressive.parallel',
    label: 'Progressive',
    path: 'series.$seriesIndex.progressive',
    control: 'number',
    defaultValue: 200,
    visibleWhen: isParallelSeries,
    group: 'Parallel Style',
    complexity: 'advanced',
    helpText: 'Progressive rendering chunk size for large datasets.',
  },
  {
    key: 'series.encode.parallel.json',
    label: 'Encode (JSON)',
    path: 'series.$seriesIndex.encode',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: {},
    visibleWhen: isParallelSeries,
    group: 'Parallel Mapping',
    complexity: 'expert',
    helpText: 'Advanced encode mapping for parallel dimensions.',
    placeholder: '{"tooltip": [0,1,2]}',
  },
  {
    key: 'series.dimensions.parallel.json',
    label: 'Dimensions (JSON)',
    path: 'series.$seriesIndex.dimensions',
    control: 'textarea',
    textareaMode: 'json',
    defaultValue: [],
    visibleWhen: isParallelSeries,
    group: 'Parallel Mapping',
    complexity: 'expert',
    helpText: 'Optional per-series dimensions override.',
    placeholder: '["A", "B", "C"]',
  },
];
