import type { FieldSchema } from '../../types/editor';
import { isPieSeries } from '../helpers/fieldBuilders';

export const pieSeriesFields: FieldSchema[] = [
  {
    key: 'series.radius',
    label: 'Radius',
    path: 'series.$seriesIndex.radius',
    control: 'text',
    valueEditor: 'tuple',
    tupleLabels: ['Inner Radius', 'Outer Radius'],
    defaultValue: ['0%', '55%'],
    placeholder: '55%',
    visibleWhen: isPieSeries,
    helpText: 'Pie radius values; use inner + outer radius for donut charts.',
  },
  {
    key: 'series.center',
    label: 'Center',
    path: 'series.$seriesIndex.center',
    control: 'text',
    valueEditor: 'tuple',
    tupleLabels: ['Center X', 'Center Y'],
    defaultValue: ['50%', '50%'],
    placeholder: '50%',
    visibleWhen: isPieSeries,
    helpText: 'Center coordinates for pie position.',
  },
  {
    key: 'series.roseType',
    label: 'Rose Type',
    path: 'series.$seriesIndex.roseType',
    control: 'select',
    defaultValue: '',
    visibleWhen: isPieSeries,
    complexity: 'advanced',
    helpText: 'Enable rose chart mode.',
    options: [
      { label: 'None', value: '' },
      { label: 'Radius', value: 'radius' },
      { label: 'Area', value: 'area' },
    ],
  },
  {
    key: 'series.stillShowZeroSum',
    label: 'Still Show Zero Sum',
    path: 'series.$seriesIndex.stillShowZeroSum',
    control: 'checkbox',
    defaultValue: true,
    visibleWhen: isPieSeries,
    complexity: 'advanced',
    helpText: 'Show pie even when all values sum to zero.',
  },
  {
    key: 'series.label.alignTo',
    label: 'Label Align To',
    path: 'series.$seriesIndex.label.alignTo',
    control: 'select',
    defaultValue: 'none',
    visibleWhen: isPieSeries,
    complexity: 'advanced',
    helpText: 'Align pie labels relative to slice and label line.',
    options: [
      { label: 'None', value: 'none' },
      { label: 'Label Line', value: 'labelLine' },
      { label: 'Edge', value: 'edge' },
    ],
  },
];
