import type { FieldSchema } from '../../types/editor';
import { isScatterSeries } from '../helpers/fieldBuilders';

export const scatterSeriesFields: FieldSchema[] = [
  {
    key: 'series.coordinateSystem.scatter',
    label: 'Coordinate System (Scatter)',
    path: 'series.$seriesIndex.coordinateSystem',
    control: 'select',
    defaultValue: 'cartesian2d',
    group: 'Scatter Mapping',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    helpText: 'Choose coordinate system for scatter points.',
    options: [
      { label: 'Cartesian 2D', value: 'cartesian2d' },
      { label: 'Geo', value: 'geo' },
      { label: 'Polar', value: 'polar' },
      { label: 'Calendar', value: 'calendar' },
      { label: 'Single Axis', value: 'singleAxis' },
    ],
  },
  {
    key: 'series.symbol.scatter',
    label: 'Symbol',
    path: 'series.$seriesIndex.symbol',
    control: 'select',
    defaultValue: 'circle',
    group: 'Scatter Style',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    helpText: 'Point marker shape for scatter points.',
    options: [
      { label: 'Circle', value: 'circle' },
      { label: 'Rect', value: 'rect' },
      { label: 'Round Rect', value: 'roundRect' },
      { label: 'Triangle', value: 'triangle' },
      { label: 'Diamond', value: 'diamond' },
      { label: 'Pin', value: 'pin' },
      { label: 'Arrow', value: 'arrow' },
      { label: 'None', value: 'none' },
    ],
  },
  {
    key: 'series.symbolSize.scatter',
    label: 'Symbol Size',
    path: 'series.$seriesIndex.symbolSize',
    control: 'number',
    defaultValue: 14,
    group: 'Scatter Style',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    helpText: 'Marker size in pixels.',
  },
  {
    key: 'series.itemStyle.color.scatter',
    label: 'Point Color',
    path: 'series.$seriesIndex.itemStyle.color',
    control: 'text',
    defaultValue: '#3b82f6',
    group: 'Scatter Style',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    helpText: 'Color for scatter points.',
  },
  {
    key: 'series.itemStyle.opacity.scatter',
    label: 'Point Opacity',
    path: 'series.$seriesIndex.itemStyle.opacity',
    control: 'number',
    defaultValue: 0.85,
    group: 'Scatter Style',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    helpText: 'Opacity for scatter points (0 to 1).',
  },
  {
    key: 'series.encode.x.scatter',
    label: 'Encode X (Scatter)',
    path: 'series.$seriesIndex.encode.x',
    control: 'text',
    defaultValue: '0',
    group: 'Scatter Mapping',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    placeholder: '0 / X',
    helpText: 'Dimension index/name used for X values.',
  },
  {
    key: 'series.encode.y.scatter',
    label: 'Encode Y (Scatter)',
    path: 'series.$seriesIndex.encode.y',
    control: 'text',
    defaultValue: '1',
    group: 'Scatter Mapping',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    placeholder: '1 / Y',
    helpText: 'Dimension index/name used for Y values.',
  },
  {
    key: 'series.encode.tooltip.scatter',
    label: 'Encode Tooltip (Scatter)',
    path: 'series.$seriesIndex.encode.tooltip',
    control: 'textarea',
    valueEditor: 'string-array',
    defaultValue: ['0', '1'],
    group: 'Scatter Mapping',
    complexity: 'advanced',
    visibleWhen: isScatterSeries,
    helpText: 'Dimensions shown in scatter tooltip (one per line).',
  },
];
