import type { SectionSchema } from '../../types/editor';
import { createPositionFields, usesCalendarCoordinates } from '../helpers/fieldBuilders';

export const defaultCalendarItem = {
  range: '2026',
  orient: 'horizontal',
  cellSize: ['auto', 18],
  left: 'center',
  top: 60,
  right: 'auto',
  bottom: 'auto',
  splitLine: {
    show: true,
    lineStyle: {
      color: '#d1d5db',
    },
  },
  itemStyle: {
    borderColor: '#e2e8f0',
    borderWidth: 1,
  },
  yearLabel: {
    show: true,
  },
  monthLabel: {
    show: true,
  },
  dayLabel: {
    show: true,
  },
};

export const calendarSection: SectionSchema = {
  id: 'calendar',
  title: 'Calendar',
  arrayBinding: {
    id: 'calendar',
    path: 'calendar',
    indexToken: '$calendarIndex',
    itemLabel: 'Calendar',
    defaultItem: defaultCalendarItem,
    minItems: 0,
  },
  fields: [
    {
      key: 'calendar.range',
      label: 'Range',
      path: 'calendar.$calendarIndex.range',
      control: 'text',
      defaultValue: '2026',
      visibleWhen: usesCalendarCoordinates,
      helpText: 'Calendar range: year, month, date range, or custom interval.',
      placeholder: '2026 / 2026-03 / ["2026-01-01","2026-12-31"]',
    },
    {
      key: 'calendar.orient',
      label: 'Orient',
      path: 'calendar.$calendarIndex.orient',
      control: 'select',
      defaultValue: 'horizontal',
      visibleWhen: usesCalendarCoordinates,
      helpText: 'Calendar layout orientation.',
      options: [
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
    },
    {
      key: 'calendar.cellSize',
      label: 'Cell Size',
      path: 'calendar.$calendarIndex.cellSize',
      control: 'text',
      valueEditor: 'tuple',
      tupleLabels: ['Width', 'Height'],
      defaultValue: ['auto', '18'],
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Calendar cell size (number or auto).',
    },
    ...createPositionFields({
      keyPrefix: 'calendar',
      pathPrefix: 'calendar.$calendarIndex',
      include: ['left', 'right', 'top', 'bottom'],
      defaultValues: { left: 'center', right: 'auto', top: '60', bottom: 'auto' },
      visibleWhen: usesCalendarCoordinates,
      helpText: 'Position selected calendar on the canvas.',
    }),
    {
      key: 'calendar.splitLine.show',
      label: 'Split Line Show',
      path: 'calendar.$calendarIndex.splitLine.show',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Show grid split lines between calendar cells.',
    },
    {
      key: 'calendar.splitLine.color',
      label: 'Split Line Color',
      path: 'calendar.$calendarIndex.splitLine.lineStyle.color',
      control: 'text',
      defaultValue: '#d1d5db',
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Split line color.',
    },
    {
      key: 'calendar.itemStyle.borderColor',
      label: 'Cell Border Color',
      path: 'calendar.$calendarIndex.itemStyle.borderColor',
      control: 'text',
      defaultValue: '#e2e8f0',
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Cell border color.',
    },
    {
      key: 'calendar.itemStyle.borderWidth',
      label: 'Cell Border Width',
      path: 'calendar.$calendarIndex.itemStyle.borderWidth',
      control: 'number',
      defaultValue: 1,
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Cell border width.',
    },
    {
      key: 'calendar.yearLabel.show',
      label: 'Year Label Show',
      path: 'calendar.$calendarIndex.yearLabel.show',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Show year label.',
    },
    {
      key: 'calendar.monthLabel.show',
      label: 'Month Label Show',
      path: 'calendar.$calendarIndex.monthLabel.show',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Show month labels.',
    },
    {
      key: 'calendar.dayLabel.show',
      label: 'Day Label Show',
      path: 'calendar.$calendarIndex.dayLabel.show',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: usesCalendarCoordinates,
      complexity: 'advanced',
      helpText: 'Show weekday/day labels.',
    },
  ],
};
