import type { EditorContext, SectionSchema } from '../../types/editor';
import { usesCartesianAxes } from '../helpers/fieldBuilders';

const asRecord = (value: unknown): Record<string, unknown> | undefined => {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return undefined;
};

const getSelectedDataZoom = (context: EditorContext): Record<string, unknown> | undefined => {
  const source = context.option.dataZoom;
  if (Array.isArray(source)) {
    return asRecord(source[context.selectedDataZoomIndex]);
  }

  return asRecord(source);
};

const isSliderDataZoom = (context: EditorContext): boolean => {
  if (!usesCartesianAxes(context)) {
    return false;
  }

  const selected = getSelectedDataZoom(context);
  const type = selected?.type;
  return typeof type === 'string' ? type === 'slider' : true;
};

export const defaultDataZoomItem = {
  type: 'slider',
  show: true,
  orient: 'horizontal',
  start: 0,
  end: 100,
  startValue: '',
  endValue: '',
  minSpan: 0,
  maxSpan: 100,
  minValueSpan: 0,
  maxValueSpan: 0,
  filterMode: 'filter',
  zoomLock: false,
  realtime: true,
  moveOnMouseMove: true,
  zoomOnMouseWheel: true,
  moveOnMouseWheel: false,
  preventDefaultMouseMove: true,
  xAxisIndex: 0,
  yAxisIndex: 0,
  brushSelect: true,
  throttle: 100,
  backgroundColor: 'rgba(47,69,84,0)',
  fillerColor: 'rgba(167,183,204,0.4)',
  borderColor: '#ddd',
  handleSize: '100%',
  handleIcon: '',
  showDataShadow: true,
  showDetail: true,
  showLabel: true,
  labelFormatter: '',
};

export const dataZoomSection: SectionSchema = {
  id: 'dataZoom',
  title: 'DataZoom',
  arrayBinding: {
    id: 'dataZoom',
    path: 'dataZoom',
    indexToken: '$dataZoomIndex',
    itemLabel: 'DataZoom',
    defaultItem: defaultDataZoomItem,
    minItems: 0,
  },
  fields: [
    {
      key: 'dataZoom.type',
      label: 'Type',
      path: 'dataZoom.$dataZoomIndex.type',
      control: 'select',
      defaultValue: 'slider',
      group: 'Basic',
      visibleWhen: usesCartesianAxes,
      keywords: ['inside', 'slider', 'zoom'],
      helpText: 'Slider is visible control; inside reacts to wheel/gesture.',
      options: [
        { label: 'Slider', value: 'slider' },
        { label: 'Inside', value: 'inside' },
      ],
    },
    {
      key: 'dataZoom.show',
      label: 'Show',
      path: 'dataZoom.$dataZoomIndex.show',
      control: 'checkbox',
      defaultValue: true,
      group: 'Basic',
      visibleWhen: usesCartesianAxes,
      keywords: ['visibility'],
      helpText: 'Show or hide this data zoom control.',
    },
    {
      key: 'dataZoom.orient',
      label: 'Orient',
      path: 'dataZoom.$dataZoomIndex.orient',
      control: 'select',
      defaultValue: 'horizontal',
      group: 'Basic',
      visibleWhen: usesCartesianAxes,
      keywords: ['direction', 'orientation'],
      helpText: 'Orientation of slider control.',
      options: [
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
    },
    {
      key: 'dataZoom.xAxisIndex',
      label: 'X Axis Index',
      path: 'dataZoom.$dataZoomIndex.xAxisIndex',
      control: 'number',
      defaultValue: 0,
      group: 'Axis Target',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      keywords: ['axis binding', 'target axis'],
      helpText: 'Target xAxis index (usually 0).',
    },
    {
      key: 'dataZoom.yAxisIndex',
      label: 'Y Axis Index',
      path: 'dataZoom.$dataZoomIndex.yAxisIndex',
      control: 'number',
      defaultValue: 0,
      group: 'Axis Target',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      keywords: ['axis binding', 'target axis'],
      helpText: 'Target yAxis index (usually 0).',
    },
    {
      key: 'dataZoom.start',
      label: 'Start',
      path: 'dataZoom.$dataZoomIndex.start',
      control: 'number',
      defaultValue: 0,
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      keywords: ['range', 'percentage'],
      helpText: 'Visible range start percentage.',
    },
    {
      key: 'dataZoom.end',
      label: 'End',
      path: 'dataZoom.$dataZoomIndex.end',
      control: 'number',
      defaultValue: 100,
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      keywords: ['range', 'percentage'],
      helpText: 'Visible range end percentage.',
    },
    {
      key: 'dataZoom.startValue',
      label: 'Start Value',
      path: 'dataZoom.$dataZoomIndex.startValue',
      control: 'text',
      defaultValue: '',
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Optional absolute start value instead of percentage.',
    },
    {
      key: 'dataZoom.endValue',
      label: 'End Value',
      path: 'dataZoom.$dataZoomIndex.endValue',
      control: 'text',
      defaultValue: '',
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Optional absolute end value instead of percentage.',
    },
    {
      key: 'dataZoom.minSpan',
      label: 'Min Span',
      path: 'dataZoom.$dataZoomIndex.minSpan',
      control: 'number',
      defaultValue: 0,
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Minimum window span in percentage points.',
    },
    {
      key: 'dataZoom.maxSpan',
      label: 'Max Span',
      path: 'dataZoom.$dataZoomIndex.maxSpan',
      control: 'number',
      defaultValue: 100,
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Maximum window span in percentage points.',
    },
    {
      key: 'dataZoom.minValueSpan',
      label: 'Min Value Span',
      path: 'dataZoom.$dataZoomIndex.minValueSpan',
      control: 'number',
      defaultValue: 0,
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'expert',
      helpText: 'Minimum window span in data value units.',
    },
    {
      key: 'dataZoom.maxValueSpan',
      label: 'Max Value Span',
      path: 'dataZoom.$dataZoomIndex.maxValueSpan',
      control: 'number',
      defaultValue: 0,
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'expert',
      helpText: 'Maximum window span in data value units.',
    },
    {
      key: 'dataZoom.filterMode',
      label: 'Filter Mode',
      path: 'dataZoom.$dataZoomIndex.filterMode',
      control: 'select',
      defaultValue: 'filter',
      group: 'Range',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      keywords: ['filter', 'weakFilter', 'empty', 'none'],
      helpText: 'How data outside range should be handled.',
      options: [
        { label: 'Filter', value: 'filter' },
        { label: 'Weak Filter', value: 'weakFilter' },
        { label: 'Empty', value: 'empty' },
        { label: 'None', value: 'none' },
      ],
    },
    {
      key: 'dataZoom.zoomLock',
      label: 'Zoom Lock',
      path: 'dataZoom.$dataZoomIndex.zoomLock',
      control: 'checkbox',
      defaultValue: false,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Lock zoom span and allow panning only.',
    },
    {
      key: 'dataZoom.realtime',
      label: 'Realtime',
      path: 'dataZoom.$dataZoomIndex.realtime',
      control: 'checkbox',
      defaultValue: true,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Update chart continuously while dragging zoom controls.',
    },
    {
      key: 'dataZoom.moveOnMouseMove',
      label: 'Move On Mouse Move',
      path: 'dataZoom.$dataZoomIndex.moveOnMouseMove',
      control: 'checkbox',
      defaultValue: true,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Allow panning while moving the mouse.',
    },
    {
      key: 'dataZoom.zoomOnMouseWheel',
      label: 'Zoom On Mouse Wheel',
      path: 'dataZoom.$dataZoomIndex.zoomOnMouseWheel',
      control: 'checkbox',
      defaultValue: true,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Enable zoom by mouse wheel.',
    },
    {
      key: 'dataZoom.moveOnMouseWheel',
      label: 'Move On Mouse Wheel',
      path: 'dataZoom.$dataZoomIndex.moveOnMouseWheel',
      control: 'checkbox',
      defaultValue: false,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Pan on mouse wheel instead of zooming.',
    },
    {
      key: 'dataZoom.preventDefaultMouseMove',
      label: 'Prevent Default Mouse Move',
      path: 'dataZoom.$dataZoomIndex.preventDefaultMouseMove',
      control: 'checkbox',
      defaultValue: true,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'expert',
      helpText: 'Prevent default browser behavior during mouse move interactions.',
    },
    {
      key: 'dataZoom.brushSelect',
      label: 'Brush Select',
      path: 'dataZoom.$dataZoomIndex.brushSelect',
      control: 'checkbox',
      defaultValue: true,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Enable brushing to select a zoom range.',
    },
    {
      key: 'dataZoom.throttle',
      label: 'Throttle',
      path: 'dataZoom.$dataZoomIndex.throttle',
      control: 'number',
      defaultValue: 100,
      group: 'Interaction',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      helpText: 'Throttle interval (ms) for interaction updates.',
    },
    {
      key: 'dataZoom.backgroundColor.slider',
      label: 'Background Color',
      path: 'dataZoom.$dataZoomIndex.backgroundColor',
      control: 'text',
      defaultValue: 'rgba(47,69,84,0)',
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Slider background color.',
    },
    {
      key: 'dataZoom.fillerColor.slider',
      label: 'Filler Color',
      path: 'dataZoom.$dataZoomIndex.fillerColor',
      control: 'text',
      defaultValue: 'rgba(167,183,204,0.4)',
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Color for selected slider window.',
    },
    {
      key: 'dataZoom.borderColor.slider',
      label: 'Border Color',
      path: 'dataZoom.$dataZoomIndex.borderColor',
      control: 'text',
      defaultValue: '#ddd',
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Slider border color.',
    },
    {
      key: 'dataZoom.handleSize.slider',
      label: 'Handle Size',
      path: 'dataZoom.$dataZoomIndex.handleSize',
      control: 'text',
      defaultValue: '100%',
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Slider handle size (pixels or percent).',
    },
    {
      key: 'dataZoom.handleIcon.slider',
      label: 'Handle Icon',
      path: 'dataZoom.$dataZoomIndex.handleIcon',
      control: 'text',
      defaultValue: '',
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'expert',
      helpText: 'Custom SVG path string for slider handles.',
    },
    {
      key: 'dataZoom.showDataShadow.slider',
      label: 'Show Data Shadow',
      path: 'dataZoom.$dataZoomIndex.showDataShadow',
      control: 'checkbox',
      defaultValue: true,
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Show mini data shadow behind the slider.',
    },
    {
      key: 'dataZoom.showDetail.slider',
      label: 'Show Detail',
      path: 'dataZoom.$dataZoomIndex.showDetail',
      control: 'checkbox',
      defaultValue: true,
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Show detail values while dragging slider handles.',
    },
    {
      key: 'dataZoom.showLabel.slider',
      label: 'Show Label',
      path: 'dataZoom.$dataZoomIndex.showLabel',
      control: 'checkbox',
      defaultValue: true,
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'advanced',
      helpText: 'Show labels on the slider axis.',
    },
    {
      key: 'dataZoom.labelFormatter.slider',
      label: 'Label Formatter',
      path: 'dataZoom.$dataZoomIndex.labelFormatter',
      control: 'textarea',
      textareaMode: 'plain',
      defaultValue: '',
      group: 'Slider Style',
      visibleWhen: isSliderDataZoom,
      complexity: 'expert',
      helpText: 'Custom formatter text/function for slider labels.',
      placeholder: '{value}',
    },
  ],
};
