import type { SectionSchema } from '../../types/editor';

export const dimensionsSection: SectionSchema = {
  id: 'dimensions',
  title: 'Dimensions',
  fields: [
    {
      key: 'dataset.dimensions',
      label: 'Dataset Dimension Names',
      path: 'dataset.$datasetIndex.dimensions',
      control: 'textarea',
      valueEditor: 'string-array',
      defaultValue: [],
      complexity: 'advanced',
      group: 'Dataset',
      helpText: 'Define dataset dimension names (one dimension per line).',
    },
    {
      key: 'dataset.dimensions.json',
      label: 'Dataset Dimensions (JSON Fallback)',
      path: 'dataset.$datasetIndex.dimensions',
      control: 'textarea',
      textareaMode: 'json',
      defaultValue: [],
      complexity: 'expert',
      group: 'Dataset',
      placeholder: '["date", {"name":"sales","type":"float"}]',
      helpText: 'Advanced dimension definitions as raw JSON.',
    },
    {
      key: 'series.dimensions',
      label: 'Series Dimension Names',
      path: 'series.$seriesIndex.dimensions',
      control: 'textarea',
      valueEditor: 'string-array',
      defaultValue: [],
      complexity: 'advanced',
      group: 'Series',
      helpText: 'Optional per-series dimensions override (one per line).',
    },
    {
      key: 'series.dimensions.json',
      label: 'Series Dimensions (JSON Fallback)',
      path: 'series.$seriesIndex.dimensions',
      control: 'textarea',
      textareaMode: 'json',
      defaultValue: [],
      complexity: 'expert',
      group: 'Series',
      placeholder: '["date", {"name":"sales","type":"float"}]',
      helpText: 'Advanced series dimension definitions as raw JSON.',
    },
  ],
};
