import type { SectionSchema } from '../../types/editor';
import { createPositionFields, usesGeoCoordinates } from '../helpers/fieldBuilders';

export const defaultGeoItem = {
  map: 'world-lite',
  roam: true,
  zoom: 1.1,
  center: [0, 20],
  left: 'center',
  right: 'auto',
  top: 'middle',
  bottom: 'auto',
  label: {
    show: false,
  },
  itemStyle: {
    areaColor: '#f8fafc',
    borderColor: '#64748b',
  },
};

export const geoSection: SectionSchema = {
  id: 'geo',
  title: 'Geo',
  arrayBinding: {
    id: 'geo',
    path: 'geo',
    indexToken: '$geoIndex',
    itemLabel: 'Geo',
    defaultItem: defaultGeoItem,
    minItems: 0,
  },
  fields: [
    {
      key: 'geo.map',
      label: 'Map',
      path: 'geo.$geoIndex.map',
      control: 'text',
      defaultValue: 'world-lite',
      visibleWhen: usesGeoCoordinates,
      helpText: 'Registered map name used by geo coordinate system.',
      placeholder: 'world-lite',
    },
    {
      key: 'geo.roam',
      label: 'Roam',
      path: 'geo.$geoIndex.roam',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: usesGeoCoordinates,
      helpText: 'Allow panning and zooming on geo component.',
    },
    {
      key: 'geo.zoom',
      label: 'Zoom',
      path: 'geo.$geoIndex.zoom',
      control: 'number',
      defaultValue: 1.1,
      visibleWhen: usesGeoCoordinates,
      complexity: 'advanced',
      helpText: 'Initial geo zoom level.',
    },
    {
      key: 'geo.center',
      label: 'Center',
      path: 'geo.$geoIndex.center',
      control: 'text',
      valueEditor: 'tuple',
      tupleLabels: ['Longitude', 'Latitude'],
      defaultValue: ['0', '20'],
      visibleWhen: usesGeoCoordinates,
      complexity: 'advanced',
      helpText: 'Initial geo center coordinates.',
    },
    ...createPositionFields({
      keyPrefix: 'geo',
      pathPrefix: 'geo.$geoIndex',
      include: ['left', 'right', 'top', 'bottom'],
      defaultValues: { left: 'center', right: 'auto', top: 'middle', bottom: 'auto' },
      visibleWhen: usesGeoCoordinates,
      helpText: 'Position selected geo component.',
    }),
    {
      key: 'geo.label.show',
      label: 'Label Show',
      path: 'geo.$geoIndex.label.show',
      control: 'checkbox',
      defaultValue: false,
      visibleWhen: usesGeoCoordinates,
      complexity: 'advanced',
      helpText: 'Show geo region labels.',
    },
    {
      key: 'geo.itemStyle.areaColor',
      label: 'Area Color',
      path: 'geo.$geoIndex.itemStyle.areaColor',
      control: 'text',
      defaultValue: '#f8fafc',
      visibleWhen: usesGeoCoordinates,
      complexity: 'advanced',
      helpText: 'Fill color for map regions.',
    },
    {
      key: 'geo.itemStyle.borderColor',
      label: 'Border Color',
      path: 'geo.$geoIndex.itemStyle.borderColor',
      control: 'text',
      defaultValue: '#64748b',
      visibleWhen: usesGeoCoordinates,
      complexity: 'advanced',
      helpText: 'Border color for map regions.',
    },
  ],
};
