import type { SectionSchema } from '../../types/editor';

export const globalSection: SectionSchema = {
  id: 'global',
  title: 'Global',
  fields: [
    {
      key: 'global.backgroundColor',
      label: 'Background Color',
      path: 'backgroundColor',
      control: 'text',
      defaultValue: '#ffffff',
      placeholder: '#ffffff / transparent',
      group: 'Appearance',
      helpText: 'Chart canvas background color.',
    },
    {
      key: 'global.color',
      label: 'Color Palette',
      path: 'color',
      control: 'textarea',
      valueEditor: 'color-array',
      defaultValue: ['#5470c6', '#91cc75', '#fac858', '#ee6666', '#73c0de'],
      group: 'Appearance',
      complexity: 'advanced',
      helpText: 'Default series color palette (one color per line).',
    },
    {
      key: 'global.textStyle.color',
      label: 'Default Text Color',
      path: 'textStyle.color',
      control: 'text',
      defaultValue: '#333333',
      group: 'Appearance',
      helpText: 'Global text color fallback for chart labels.',
    },
    {
      key: 'global.textStyle.fontSize',
      label: 'Default Font Size',
      path: 'textStyle.fontSize',
      control: 'number',
      defaultValue: 12,
      group: 'Appearance',
      helpText: 'Global text size fallback in pixels.',
    },
    {
      key: 'global.animation',
      label: 'Animation',
      path: 'animation',
      control: 'checkbox',
      defaultValue: true,
      group: 'Animation',
      helpText: 'Enable chart animations.',
    },
    {
      key: 'global.animationDuration',
      label: 'Animation Duration',
      path: 'animationDuration',
      control: 'number',
      defaultValue: 1000,
      group: 'Animation',
      complexity: 'advanced',
      helpText: 'Initial animation duration in milliseconds.',
    },
    {
      key: 'global.animationDurationUpdate',
      label: 'Update Duration',
      path: 'animationDurationUpdate',
      control: 'number',
      defaultValue: 300,
      group: 'Animation',
      complexity: 'advanced',
      helpText: 'Update animation duration in milliseconds.',
    },
    {
      key: 'global.aria.show',
      label: 'ARIA Show',
      path: 'aria.show',
      control: 'checkbox',
      defaultValue: false,
      group: 'Accessibility',
      complexity: 'advanced',
      helpText: 'Enable ARIA accessibility description output.',
    },
    {
      key: 'global.aria.description',
      label: 'ARIA Description',
      path: 'aria.description',
      control: 'textarea',
      textareaMode: 'plain',
      defaultValue: '',
      group: 'Accessibility',
      complexity: 'expert',
      placeholder: 'Describe chart for assistive technologies',
      helpText: 'Custom accessibility description for screen readers.',
    },
  ],
};
