import type { FieldSchema, SectionSchema } from '../../types/editor';
import { createBoxModelFields, createPositionFields, createShowField, usesCartesianAxes } from '../helpers/fieldBuilders';

export const defaultGridItem = {
  show: false,
  left: '10%',
  right: '10%',
  top: '14%',
  bottom: '12%',
  width: '',
  height: '',
  containLabel: true,
  backgroundColor: 'transparent',
  borderColor: '#000000',
  borderWidth: 0,
  shadowBlur: 0,
  shadowColor: 'rgba(0,0,0,0.2)',
};

export const gridSection: SectionSchema = {
  id: 'grid',
  title: 'Grid',
  arrayBinding: {
    id: 'grid',
    path: 'grid',
    indexToken: '$gridIndex',
    itemLabel: 'Grid',
    defaultItem: defaultGridItem,
    minItems: 0,
  },
  fields: [
    createShowField({
      key: 'grid.show',
      path: 'grid.$gridIndex.show',
      defaultValue: false,
      visibleWhen: usesCartesianAxes,
      helpText: 'Show selected grid container frame.',
    }),
    ...createPositionFields({
      keyPrefix: 'grid',
      pathPrefix: 'grid.$gridIndex',
      include: ['left', 'right', 'top', 'bottom'],
      defaultValues: { left: '10%', right: '10%', top: '14%', bottom: '12%' },
      visibleWhen: usesCartesianAxes,
      helpText: 'Adjust selected grid bounds.',
    }),
    {
      key: 'grid.width',
      label: 'Width',
      path: 'grid.$gridIndex.width',
      control: 'text',
      defaultValue: '',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      group: 'Layout',
      placeholder: 'auto / 70% / 800',
      helpText: 'Optional explicit grid width.',
    },
    {
      key: 'grid.height',
      label: 'Height',
      path: 'grid.$gridIndex.height',
      control: 'text',
      defaultValue: '',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      group: 'Layout',
      placeholder: 'auto / 60% / 420',
      helpText: 'Optional explicit grid height.',
    },
    {
      key: 'grid.containLabel',
      label: 'Contain Label',
      path: 'grid.$gridIndex.containLabel',
      control: 'checkbox',
      defaultValue: true,
      group: 'Layout',
      visibleWhen: usesCartesianAxes,
      helpText: 'Expand selected grid to include axis labels.',
    },
    ...createBoxModelFields({
      keyPrefix: 'grid',
      pathPrefix: 'grid.$gridIndex',
      defaultBackgroundColor: 'transparent',
      defaultBorderColor: '#000000',
      defaultBorderWidth: 0,
      includePadding: false,
      visibleWhen: usesCartesianAxes,
    }).map((field): FieldSchema => ({
      ...field,
      group: 'Style',
      complexity: 'advanced',
    })),
    {
      key: 'grid.shadowBlur',
      label: 'Shadow Blur',
      path: 'grid.$gridIndex.shadowBlur',
      control: 'number',
      defaultValue: 0,
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      group: 'Style',
      helpText: 'Blur radius for grid shadow.',
    },
    {
      key: 'grid.shadowColor',
      label: 'Shadow Color',
      path: 'grid.$gridIndex.shadowColor',
      control: 'text',
      defaultValue: 'rgba(0,0,0,0.2)',
      visibleWhen: usesCartesianAxes,
      complexity: 'advanced',
      group: 'Style',
      helpText: 'Color for grid shadow effect.',
      placeholder: 'rgba(0,0,0,0.2)',
    },
  ],
};
