import type { SectionSchema } from '../../types/editor';
import { createBoxModelFields, createPositionFields, createShowField, createTextStyleFields } from '../helpers/fieldBuilders';

export const legendSection: SectionSchema = {
  id: 'legend',
  title: 'Legend',
  fields: [
    createShowField({
      key: 'legend.show',
      path: 'legend.show',
      defaultValue: true,
      helpText: 'Display or hide legend entries.',
    }),
    {
      key: 'legend.orient',
      label: 'Orient',
      path: 'legend.orient',
      control: 'select',
      defaultValue: 'horizontal',
      helpText: 'Set legend item flow direction.',
      options: [
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
    },
    {
      key: 'legend.align',
      label: 'Align',
      path: 'legend.align',
      control: 'select',
      defaultValue: 'auto',
      complexity: 'advanced' as const,
      keywords: ['alignment', 'text', 'legend'],
      description: 'Align legend marker and text layout.',
      helpText: 'Mainly useful for vertical legends.',
      options: [
        { label: 'Auto', value: 'auto' },
        { label: 'Left', value: 'left' },
        { label: 'Right', value: 'right' },
      ],
    },
    ...createPositionFields({
      keyPrefix: 'legend',
      pathPrefix: 'legend',
      include: ['left', 'right', 'top', 'bottom'],
      defaultValues: { left: 'center', right: 'auto', top: 'top', bottom: 'auto' },
      helpText: 'Set legend position.',
    }),
    {
      key: 'legend.icon',
      label: 'Icon',
      path: 'legend.icon',
      control: 'text',
      defaultValue: 'roundRect',
      keywords: ['symbol', 'marker', 'legend'],
      description: 'Legend marker icon shape or custom image path.',
      helpText: 'Supports built-in shapes (rect/circle/roundRect/diamond) or image:// URLs.',
      placeholder: 'roundRect / circle / image://...',
    },
    {
      key: 'legend.itemWidth',
      label: 'Item Width',
      path: 'legend.itemWidth',
      control: 'number',
      defaultValue: 25,
      complexity: 'advanced' as const,
      keywords: ['marker', 'width', 'legend'],
      description: 'Width of legend icon marker.',
      helpText: 'Controls horizontal icon size in pixels.',
    },
    {
      key: 'legend.itemHeight',
      label: 'Item Height',
      path: 'legend.itemHeight',
      control: 'number',
      defaultValue: 14,
      complexity: 'advanced' as const,
      keywords: ['marker', 'height', 'legend'],
      description: 'Height of legend icon marker.',
      helpText: 'Controls vertical icon size in pixels.',
    },
    {
      key: 'legend.itemGap',
      label: 'Item Gap',
      path: 'legend.itemGap',
      control: 'number',
      defaultValue: 10,
      complexity: 'advanced' as const,
      keywords: ['spacing', 'gap', 'legend'],
      description: 'Gap between legend entries.',
      helpText: 'Increase for readability on dense legends.',
    },
    ...createTextStyleFields({
      keyPrefix: 'legend.textStyle',
      pathPrefix: 'legend.textStyle',
      labelPrefix: 'Text',
      defaultColor: '#e2e8f0',
      defaultFontSize: 12,
    }).map((field) => ({
      ...field,
      complexity: field.path.endsWith('.fontSize') ? ('advanced' as const) : undefined,
      keywords: field.path.endsWith('.fontSize') ? ['legend', 'font', 'size'] : ['legend', 'text', 'color'],
      description: field.path.endsWith('.fontSize') ? 'Legend text font size.' : 'Legend text color.',
    })),
    {
      key: 'legend.selectedMode',
      label: 'Selected Mode',
      path: 'legend.selectedMode',
      control: 'select',
      defaultValue: 'multiple',
      complexity: 'advanced' as const,
      keywords: ['selection', 'toggle', 'legend'],
      description: 'Control whether users can toggle multiple legend items or a single active item.',
      helpText: 'Control how legend selection behaves.',
      options: [
        { label: 'Multiple', value: 'multiple' },
        { label: 'Single', value: 'single' },
        { label: 'Disabled', value: 'false' },
      ],
    },
    {
      key: 'legend.inactiveColor',
      label: 'Inactive Color',
      path: 'legend.inactiveColor',
      control: 'text',
      defaultValue: '#64748b',
      complexity: 'advanced' as const,
      keywords: ['inactive', 'disabled', 'legend'],
      description: 'Text/icon color for deselected legend items.',
      helpText: 'Use lower contrast for inactive states.',
    },
    ...createBoxModelFields({
      keyPrefix: 'legend',
      pathPrefix: 'legend',
      defaultBackgroundColor: 'transparent',
      defaultBorderColor: '#334155',
      defaultBorderWidth: 0,
      defaultPadding: 5,
      backgroundLabel: 'Background Color',
    }).map((field) => ({
      ...field,
      complexity: 'advanced' as const,
      keywords: ['legend', 'box', 'style'],
      description: `Legend box styling option (${field.label.toLowerCase()}).`,
    })),
  ],
};
