import type { SectionSchema } from '../../types/editor';
import { isRadarSeries } from '../helpers/fieldBuilders';

export const defaultRadarItem = {
  shape: 'polygon',
  center: ['50%', '55%'],
  radius: '65%',
  splitNumber: 5,
  indicator: [
    { name: 'Quality', max: 100 },
    { name: 'Speed', max: 100 },
    { name: 'Reliability', max: 100 },
  ],
};

export const radarSection: SectionSchema = {
  id: 'radar',
  title: 'Radar Component',
  arrayBinding: {
    id: 'radar',
    path: 'radar',
    indexToken: '$radarIndex',
    itemLabel: 'Radar',
    defaultItem: defaultRadarItem,
    minItems: 0,
  },
  fields: [
    {
      key: 'radar.shape',
      label: 'Shape',
      path: 'radar.$radarIndex.shape',
      control: 'select',
      defaultValue: 'polygon',
      visibleWhen: isRadarSeries,
      helpText: 'Polygon is the common radar grid shape; circle creates circular rings.',
      options: [
        { label: 'Polygon', value: 'polygon' },
        { label: 'Circle', value: 'circle' },
      ],
    },
    {
      key: 'radar.center',
      label: 'Center',
      path: 'radar.$radarIndex.center',
      control: 'text',
      valueEditor: 'tuple',
      tupleLabels: ['Center X', 'Center Y'],
      defaultValue: ['50%', '55%'],
      visibleWhen: isRadarSeries,
      complexity: 'advanced',
      helpText: 'Center position of selected radar component.',
    },
    {
      key: 'radar.radius',
      label: 'Radius',
      path: 'radar.$radarIndex.radius',
      control: 'text',
      defaultValue: '65%',
      visibleWhen: isRadarSeries,
      complexity: 'advanced',
      placeholder: '65% / ["40%", "70%"]',
      helpText: 'Outer radius (or radius range) of selected radar component.',
    },
    {
      key: 'radar.splitNumber',
      label: 'Split Number',
      path: 'radar.$radarIndex.splitNumber',
      control: 'number',
      defaultValue: 5,
      visibleWhen: isRadarSeries,
      complexity: 'advanced',
      helpText: 'Number of rings/spokes subdivisions.',
    },
    {
      key: 'radar.indicator',
      label: 'Indicators',
      path: 'radar.$radarIndex.indicator',
      control: 'textarea',
      valueEditor: 'object-array',
      defaultValue: defaultRadarItem.indicator,
      visibleWhen: isRadarSeries,
      complexity: 'advanced',
      helpText: 'Radar indicator definitions (array of objects with name/max).',
    },
    {
      key: 'radar.indicator.json',
      label: 'Indicators (JSON Fallback)',
      path: 'radar.$radarIndex.indicator',
      control: 'textarea',
      textareaMode: 'json',
      defaultValue: defaultRadarItem.indicator,
      visibleWhen: isRadarSeries,
      complexity: 'expert',
      placeholder: '[{"name":"Quality","max":100}]',
      helpText: 'Advanced indicator structure fallback as raw JSON.',
    },
  ],
};
