import type { FieldSchema, SectionSchema } from '../../types/editor';
import { createBoxModelFields, createPositionFields, createShowField, createTextStyleFields } from '../helpers/fieldBuilders';

export const defaultTitleItem = {
  show: true,
  text: 'Chart Title',
  subtext: '',
  left: 'center',
  top: 'top',
  right: '',
  bottom: '',
  padding: 5,
  itemGap: 10,
  backgroundColor: 'transparent',
  borderColor: '#000000',
  borderWidth: 0,
  borderRadius: 0,
  link: '',
  target: 'blank',
  sublink: '',
  subtarget: 'blank',
};

export const titleSection: SectionSchema = {
  id: 'title',
  title: 'Title',
  arrayBinding: {
    id: 'title',
    path: 'title',
    indexToken: '$titleIndex',
    itemLabel: 'Title',
    defaultItem: defaultTitleItem,
    minItems: 0,
  },
  fields: [
    createShowField({
      key: 'title.show',
      path: 'title.$titleIndex.show',
      defaultValue: true,
      helpText: 'Toggle the selected title visibility.',
    }),
    {
      key: 'title.text',
      label: 'Text',
      path: 'title.$titleIndex.text',
      control: 'text',
      placeholder: 'Chart title',
      defaultValue: 'Chart Title',
      helpText: 'Main title text.',
    },
    {
      key: 'title.subtext',
      label: 'Subtext',
      path: 'title.$titleIndex.subtext',
      control: 'textarea',
      textareaMode: 'plain',
      defaultValue: '',
      placeholder: 'Optional subtitle',
      complexity: 'advanced',
      helpText: 'Optional subtitle displayed below title.',
    },
    ...createPositionFields({
      keyPrefix: 'title',
      pathPrefix: 'title.$titleIndex',
      include: ['left', 'right', 'top', 'bottom'],
      defaultValues: { left: 'center', right: '', top: 'top', bottom: '' },
      helpText: 'Position selected title.',
    }).map((field): FieldSchema => {
      if (field.path.endsWith('.right') || field.path.endsWith('.bottom')) {
        return {
          ...field,
          complexity: 'advanced',
        };
      }

      return field;
    }),
    {
      key: 'title.itemGap',
      label: 'Item Gap',
      path: 'title.$titleIndex.itemGap',
      control: 'number',
      defaultValue: 10,
      complexity: 'advanced',
      helpText: 'Spacing between title and subtitle in pixels.',
    },
    ...createBoxModelFields({
      keyPrefix: 'title',
      pathPrefix: 'title.$titleIndex',
      defaultBackgroundColor: 'transparent',
      defaultBorderColor: '#000000',
      defaultBorderWidth: 0,
      defaultBorderRadius: 0,
      defaultPadding: 5,
      includeBorderRadius: true,
      backgroundLabel: 'Background Color',
    }).map((field): FieldSchema => ({ ...field, complexity: 'advanced' })),
    {
      key: 'title.link',
      label: 'Link',
      path: 'title.$titleIndex.link',
      control: 'text',
      defaultValue: '',
      complexity: 'advanced',
      placeholder: 'https://example.com',
      helpText: 'Open this URL when title text is clicked.',
    },
    {
      key: 'title.target',
      label: 'Target',
      path: 'title.$titleIndex.target',
      control: 'select',
      defaultValue: 'blank',
      complexity: 'advanced',
      helpText: 'How to open the title link.',
      options: [
        { label: 'New Tab', value: 'blank' },
        { label: 'Same Tab', value: 'self' },
      ],
    },
    {
      key: 'title.sublink',
      label: 'Sub Link',
      path: 'title.$titleIndex.sublink',
      control: 'text',
      defaultValue: '',
      complexity: 'advanced',
      placeholder: 'https://example.com/sub',
      helpText: 'Open this URL when subtitle text is clicked.',
    },
    {
      key: 'title.subtarget',
      label: 'Sub Target',
      path: 'title.$titleIndex.subtarget',
      control: 'select',
      defaultValue: 'blank',
      complexity: 'advanced',
      helpText: 'How to open the subtitle link.',
      options: [
        { label: 'New Tab', value: 'blank' },
        { label: 'Same Tab', value: 'self' },
      ],
    },
    ...createTextStyleFields({
      keyPrefix: 'title.textStyle',
      pathPrefix: 'title.$titleIndex.textStyle',
      labelPrefix: 'Title',
      defaultColor: '#e2e8f0',
      defaultFontSize: 18,
      includeTypography: true,
      defaultFontStyle: 'normal',
      defaultFontWeight: 'bold',
      defaultFontFamily: 'sans-serif',
      defaultLineHeight: 0,
      defaultAlign: 'auto',
      typographyComplexity: 'advanced',
    }),
    ...createTextStyleFields({
      keyPrefix: 'title.subtextStyle',
      pathPrefix: 'title.$titleIndex.subtextStyle',
      labelPrefix: 'Subtext',
      defaultColor: '#94a3b8',
      defaultFontSize: 12,
      includeTypography: true,
      defaultFontStyle: 'normal',
      defaultFontWeight: 'normal',
      defaultFontFamily: 'sans-serif',
      defaultLineHeight: 0,
      defaultAlign: 'auto',
      typographyComplexity: 'advanced',
    }).map((field): FieldSchema => ({ ...field, complexity: 'advanced' as const })),
  ],
};
