import type { SectionSchema } from '../../types/editor';
import { createBoxModelFields, createShowField, createTextStyleFields } from '../helpers/fieldBuilders';

export const tooltipSection: SectionSchema = {
  id: 'tooltip',
  title: 'Tooltip',
  fields: [
    createShowField({
      key: 'tooltip.show',
      path: 'tooltip.show',
      defaultValue: true,
      helpText: 'Enable tooltip on hover.',
    }),
    {
      key: 'tooltip.trigger',
      label: 'Trigger',
      path: 'tooltip.trigger',
      control: 'select',
      defaultValue: 'axis',
      keywords: ['hover', 'interaction', 'axis', 'item'],
      description: 'Determines whether tooltips follow axis coordinates or individual data items.',
      helpText: 'Axis trigger is common for line/bar, item for pie.',
      options: [
        { label: 'Axis', value: 'axis' },
        { label: 'Item', value: 'item' },
      ],
    },
    {
      key: 'tooltip.triggerOn',
      label: 'Trigger On',
      path: 'tooltip.triggerOn',
      control: 'select',
      defaultValue: 'mousemove|click',
      complexity: 'advanced' as const,
      keywords: ['hover', 'click', 'interaction'],
      description: 'Configures which user actions trigger tooltip display.',
      helpText: 'Choose hover/click behavior for tooltip activation.',
      options: [
        { label: 'Mousemove + Click', value: 'mousemove|click' },
        { label: 'Mousemove', value: 'mousemove' },
        { label: 'Click', value: 'click' },
        { label: 'None', value: 'none' },
      ],
    },
    {
      key: 'tooltip.formatter',
      label: 'Formatter',
      path: 'tooltip.formatter',
      control: 'textarea',
      textareaMode: 'plain',
      defaultValue: '',
      placeholder: '{b}: {c}',
      helpText: 'Optional formatter text for custom tooltip output.',
    },
    {
      key: 'tooltip.valueFormatter',
      label: 'Value Formatter',
      path: 'tooltip.valueFormatter',
      control: 'textarea',
      textareaMode: 'plain',
      defaultValue: '',
      complexity: 'advanced' as const,
      keywords: ['format', 'number', 'value'],
      description: 'Formats value-only output in tooltip for each series item.',
      placeholder: '(value) => `${value} ms`',
      helpText: 'Use when you want consistent value formatting without full formatter templates.',
    },
    ...createBoxModelFields({
      keyPrefix: 'tooltip',
      pathPrefix: 'tooltip',
      defaultBackgroundColor: 'rgba(50,50,50,0.7)',
      defaultBorderColor: '#333333',
      defaultBorderWidth: 0,
      defaultPadding: 5,
    }),
    ...createTextStyleFields({
      keyPrefix: 'tooltip.textStyle',
      pathPrefix: 'tooltip.textStyle',
      labelPrefix: 'Text',
      defaultColor: '#ffffff',
      defaultFontSize: 14,
    }).map((field) => ({
      ...field,
      complexity: field.path.endsWith('.fontSize') ? ('advanced' as const) : undefined,
      keywords: field.path.endsWith('.fontSize') ? ['font', 'size', 'tooltip'] : ['text', 'color', 'tooltip'],
      description: field.path.endsWith('.fontSize')
        ? 'Tooltip text size in pixels.'
        : 'Tooltip text color.',
    })),
    {
      key: 'tooltip.extraCssText',
      label: 'Extra CSS Text',
      path: 'tooltip.extraCssText',
      control: 'text',
      defaultValue: '',
      complexity: 'expert' as const,
      keywords: ['css', 'style', 'tooltip'],
      description: 'Appends raw CSS declarations to tooltip DOM style.',
      placeholder: 'box-shadow: 0 0 8px rgba(0,0,0,0.3);',
      helpText: 'Use only for advanced custom tooltip styling.',
    },
    {
      key: 'tooltip.confine',
      label: 'Confine',
      path: 'tooltip.confine',
      control: 'checkbox',
      defaultValue: false,
      complexity: 'advanced' as const,
      keywords: ['overflow', 'viewport', 'bounds'],
      description: 'Keeps tooltip within chart container bounds.',
      helpText: 'Helpful when tooltips overflow outside small chart containers.',
    },
    {
      key: 'tooltip.appendToBody',
      label: 'Append To Body',
      path: 'tooltip.appendToBody',
      control: 'checkbox',
      defaultValue: false,
      complexity: 'expert' as const,
      keywords: ['portal', 'dom', 'overlay'],
      description: 'Renders tooltip element under document body.',
      helpText: 'Useful for complex clipping/stacking contexts.',
    },
    {
      key: 'tooltip.axisPointer.type',
      label: 'Axis Pointer Type',
      path: 'tooltip.axisPointer.type',
      control: 'select',
      defaultValue: 'line',
      complexity: 'advanced' as const,
      keywords: ['crosshair', 'pointer', 'axis'],
      description: 'Pointer style used when tooltip trigger is axis.',
      helpText: 'Line for common trends, cross for precise intersection reads.',
      options: [
        { label: 'Line', value: 'line' },
        { label: 'Shadow', value: 'shadow' },
        { label: 'Cross', value: 'cross' },
        { label: 'None', value: 'none' },
      ],
    },
    {
      key: 'tooltip.axisPointer.snap',
      label: 'Axis Pointer Snap',
      path: 'tooltip.axisPointer.snap',
      control: 'checkbox',
      defaultValue: false,
      complexity: 'advanced' as const,
      keywords: ['snap', 'data point', 'axis pointer'],
      description: 'Snaps axis pointer to nearest data point when possible.',
      helpText: 'Improves readability for dense line/bar datasets.',
    },
    {
      key: 'tooltip.order',
      label: 'Order',
      path: 'tooltip.order',
      control: 'select',
      defaultValue: 'seriesAsc',
      complexity: 'advanced' as const,
      keywords: ['sort', 'tooltip values', 'order'],
      description: 'Sort order for multiple values displayed in one tooltip.',
      helpText: 'Choose whether values are listed by series or value ranking.',
      options: [
        { label: 'Series Asc', value: 'seriesAsc' },
        { label: 'Series Desc', value: 'seriesDesc' },
        { label: 'Value Asc', value: 'valueAsc' },
        { label: 'Value Desc', value: 'valueDesc' },
      ],
    },
  ],
};
