import type { SectionSchema } from '../../types/editor';
import { createPositionFields, createShowField } from '../helpers/fieldBuilders';

const createToolboxIconStyleFields = (keyPrefix: string, pathPrefix: string) => {
  return [
    {
      key: `${keyPrefix}.color`,
      label: 'Icon Color',
      path: `${pathPrefix}.color`,
      control: 'text' as const,
      defaultValue: '#94a3b8',
      complexity: 'advanced' as const,
      group: 'Style',
      helpText: 'Default toolbox icon color.',
      placeholder: '#94a3b8 / rgba(...)',
    },
    {
      key: `${keyPrefix}.borderColor`,
      label: 'Icon Border Color',
      path: `${pathPrefix}.borderColor`,
      control: 'text' as const,
      defaultValue: '#94a3b8',
      complexity: 'advanced' as const,
      group: 'Style',
      helpText: 'Toolbox icon border color.',
      placeholder: '#94a3b8 / rgba(...)',
    },
    {
      key: `${keyPrefix}.borderWidth`,
      label: 'Icon Border Width',
      path: `${pathPrefix}.borderWidth`,
      control: 'number' as const,
      defaultValue: 1,
      complexity: 'advanced' as const,
      group: 'Style',
      helpText: 'Toolbox icon border width in pixels.',
    },
  ];
};

const createToolboxFeatureToggleField = (key: string, path: string, defaultValue: boolean, helpText: string) => ({
  ...createShowField({
    key,
    path,
    defaultValue,
    helpText,
  }),
  group: 'Features',
});

export const toolboxSection: SectionSchema = {
  id: 'toolbox',
  title: 'Toolbox',
  fields: [
    createShowField({
      key: 'toolbox.show',
      path: 'toolbox.show',
      defaultValue: false,
      helpText: 'Show toolbox actions on chart.',
    }),
    {
      key: 'toolbox.orient',
      label: 'Orient',
      path: 'toolbox.orient',
      control: 'select',
      defaultValue: 'horizontal',
      helpText: 'Orientation for toolbox icon row.',
      options: [
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
    },
    {
      key: 'toolbox.itemSize',
      label: 'Item Size',
      path: 'toolbox.itemSize',
      control: 'number',
      defaultValue: 15,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Size of toolbox icons in pixels.',
    },
    {
      key: 'toolbox.itemGap',
      label: 'Item Gap',
      path: 'toolbox.itemGap',
      control: 'number',
      defaultValue: 8,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Gap between toolbox icons in pixels.',
    },
    {
      key: 'toolbox.showTitle',
      label: 'Show Title',
      path: 'toolbox.showTitle',
      control: 'checkbox',
      defaultValue: true,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Show hover title text for toolbox features.',
    },
    ...createPositionFields({
      keyPrefix: 'toolbox',
      pathPrefix: 'toolbox',
      include: ['left', 'right', 'top', 'bottom'],
      defaultValues: { left: 'right', right: '', top: 'top', bottom: '' },
      helpText: 'Toolbox position.',
    }).map((field) => ({
      ...field,
      group: 'Layout',
    })),
    ...createToolboxIconStyleFields('toolbox.iconStyle', 'toolbox.iconStyle'),
    ...createToolboxIconStyleFields('toolbox.emphasis.iconStyle', 'toolbox.emphasis.iconStyle').map((field) => ({
      ...field,
      key: field.key.replace('toolbox.emphasis.iconStyle', 'toolbox.emphasis.iconStyle.toolbox'),
      label: field.label.replace('Icon ', 'Emphasis Icon '),
    })),
    createToolboxFeatureToggleField(
      'toolbox.feature.saveAsImage.show',
      'toolbox.feature.saveAsImage.show',
      true,
      'Enable save as image tool.',
    ),
    {
      key: 'toolbox.feature.saveAsImage.name',
      label: 'Save As Image Name',
      path: 'toolbox.feature.saveAsImage.name',
      control: 'text',
      defaultValue: 'chart',
      group: 'Features',
      complexity: 'advanced',
      helpText: 'Default filename when exporting image.',
    },
    {
      key: 'toolbox.feature.saveAsImage.type',
      label: 'Save As Image Type',
      path: 'toolbox.feature.saveAsImage.type',
      control: 'select',
      defaultValue: 'png',
      group: 'Features',
      complexity: 'advanced',
      helpText: 'Image format for save-as-image.',
      options: [
        { label: 'PNG', value: 'png' },
        { label: 'JPEG', value: 'jpeg' },
        { label: 'SVG', value: 'svg' },
      ],
    },
    createToolboxFeatureToggleField(
      'toolbox.feature.restore.show',
      'toolbox.feature.restore.show',
      true,
      'Enable restore default state tool.',
    ),
    createToolboxFeatureToggleField(
      'toolbox.feature.dataView.show',
      'toolbox.feature.dataView.show',
      false,
      'Enable raw data view popup tool.',
    ),
    {
      key: 'toolbox.feature.dataView.readOnly',
      label: 'Data View Read Only',
      path: 'toolbox.feature.dataView.readOnly',
      control: 'checkbox',
      defaultValue: false,
      group: 'Features',
      complexity: 'advanced',
      helpText: 'Make data view read-only.',
    },
    createToolboxFeatureToggleField(
      'toolbox.feature.dataZoom.show',
      'toolbox.feature.dataZoom.show',
      false,
      'Enable toolbox data zoom tool.',
    ),
    createToolboxFeatureToggleField(
      'toolbox.feature.magicType.show',
      'toolbox.feature.magicType.show',
      false,
      'Enable magic type switcher (line/bar/stack).',
    ),
    {
      key: 'toolbox.feature.magicType.type.list',
      label: 'Magic Type List',
      path: 'toolbox.feature.magicType.type',
      control: 'textarea',
      valueEditor: 'string-array',
      defaultValue: ['line', 'bar'],
      group: 'Features',
      complexity: 'advanced',
      placeholder: 'line\nbar\nstack',
      helpText: 'Series modes available in magic type (one per line).',
    },
  ],
};
