import type { EditorContext, FieldSchema, SectionSchema } from '../../types/editor';
import { createBoxModelFields, createPositionFields, createTextStyleFields } from '../helpers/fieldBuilders';
import { supportsVisualMap } from '../helpers/fieldBuilders';

const asRecord = (value: unknown): Record<string, unknown> | undefined => {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return undefined;
};

const getSelectedVisualMap = (context: EditorContext) => {
  const source = context.option.visualMap;
  if (Array.isArray(source)) {
    return asRecord(source[context.selectedVisualMapIndex]);
  }

  return asRecord(source);
};

const isPiecewiseVisualMap = (context: EditorContext) => {
  if (!supportsVisualMap(context)) {
    return false;
  }

  const visualMap = getSelectedVisualMap(context);
  const type = visualMap?.type;
  return typeof type === 'string' ? type === 'piecewise' : false;
};

export const defaultVisualMapItem = {
  show: false,
  type: 'continuous',
  min: 0,
  max: 100,
  calculable: true,
  inverse: false,
  text: ['High', 'Low'],
  textGap: 10,
  itemWidth: 20,
  itemHeight: 140,
  realtime: true,
  precision: 0,
  dimension: 0,
  seriesIndex: [0],
  left: 'left',
  right: '',
  top: 'middle',
  bottom: '',
  orient: 'vertical',
  backgroundColor: 'transparent',
  borderColor: '#000000',
  borderWidth: 0,
  padding: 8,
  textStyle: {
    color: '#e2e8f0',
    fontSize: 12,
  },
  inRange: {
    color: ['#50a3ba', '#eac736', '#d94e5d'],
    symbolSize: [10, 50],
  },
  outOfRange: {
    color: ['#94a3b8'],
    symbolSize: [6, 18],
  },
};

const visualMapFields: FieldSchema[] = [
    {
      key: 'visualMap.show',
      label: 'Show',
      path: 'visualMap.$visualMapIndex.show',
      control: 'checkbox',
      defaultValue: false,
      visibleWhen: supportsVisualMap,
      helpText: 'Enable visual mapping legend for value ranges.',
    },
    {
      key: 'visualMap.type',
      label: 'Type',
      path: 'visualMap.$visualMapIndex.type',
      control: 'select',
      defaultValue: 'continuous',
      visibleWhen: supportsVisualMap,
      helpText: 'Continuous or piecewise visual mapping.',
      options: [
        { label: 'Continuous', value: 'continuous' },
        { label: 'Piecewise', value: 'piecewise' },
      ],
    },
    {
      key: 'visualMap.calculable',
      label: 'Calculable',
      path: 'visualMap.$visualMapIndex.calculable',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'General',
      helpText: 'Allow dragging handles on visualMap to adjust ranges.',
    },
    {
      key: 'visualMap.inverse',
      label: 'Inverse',
      path: 'visualMap.$visualMapIndex.inverse',
      control: 'checkbox',
      defaultValue: false,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'General',
      helpText: 'Reverse visual mapping direction.',
    },
    {
      key: 'visualMap.min',
      label: 'Min',
      path: 'visualMap.$visualMapIndex.min',
      control: 'number',
      defaultValue: 0,
      visibleWhen: supportsVisualMap,
      helpText: 'Minimum mapped value.',
    },
    {
      key: 'visualMap.max',
      label: 'Max',
      path: 'visualMap.$visualMapIndex.max',
      control: 'number',
      defaultValue: 100,
      visibleWhen: supportsVisualMap,
      helpText: 'Maximum mapped value.',
    },
    {
      key: 'visualMap.dimension',
      label: 'Dimension',
      path: 'visualMap.$visualMapIndex.dimension',
      control: 'number',
      defaultValue: 0,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'General',
      helpText: 'Dataset dimension index used for visual mapping.',
    },
    {
      key: 'visualMap.seriesIndex',
      label: 'Series Indexes',
      path: 'visualMap.$visualMapIndex.seriesIndex',
      control: 'textarea',
      valueEditor: 'number-array',
      defaultValue: [0],
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'General',
      helpText: 'Apply mapping to these series indexes (one number per line).',
      placeholder: '0\n1',
    },
    {
      key: 'visualMap.realtime',
      label: 'Realtime',
      path: 'visualMap.$visualMapIndex.realtime',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'General',
      helpText: 'Update chart continuously while dragging mapping controller.',
    },
    {
      key: 'visualMap.precision',
      label: 'Precision',
      path: 'visualMap.$visualMapIndex.precision',
      control: 'number',
      defaultValue: 0,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'General',
      helpText: 'Decimal precision for visualMap labels.',
    },
    {
      key: 'visualMap.left',
      label: 'Left',
      path: 'visualMap.$visualMapIndex.left',
      control: 'text',
      defaultValue: 'left',
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Horizontal placement.',
    },
    ...createPositionFields({
      keyPrefix: 'visualMap',
      pathPrefix: 'visualMap.$visualMapIndex',
      include: ['right', 'bottom'],
      defaultValues: { right: '', bottom: '' },
      visibleWhen: supportsVisualMap,
      helpText: 'Optional additional visualMap offsets.',
    }).map((field): FieldSchema => ({
      ...field,
      complexity: 'advanced',
      group: 'Layout',
    })),
    {
      key: 'visualMap.top',
      label: 'Top',
      path: 'visualMap.$visualMapIndex.top',
      control: 'text',
      defaultValue: 'middle',
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Vertical placement.',
    },
    {
      key: 'visualMap.orient',
      label: 'Orient',
      path: 'visualMap.$visualMapIndex.orient',
      control: 'select',
      defaultValue: 'vertical',
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'VisualMap orientation.',
      options: [
        { label: 'Vertical', value: 'vertical' },
        { label: 'Horizontal', value: 'horizontal' },
      ],
    },
    {
      key: 'visualMap.text',
      label: 'Text Labels',
      path: 'visualMap.$visualMapIndex.text',
      control: 'textarea',
      valueEditor: 'string-array',
      defaultValue: ['High', 'Low'],
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Labels for high/low ends (one per line).',
      placeholder: 'High\nLow',
    },
    {
      key: 'visualMap.textGap',
      label: 'Text Gap',
      path: 'visualMap.$visualMapIndex.textGap',
      control: 'number',
      defaultValue: 10,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Gap between labels and controller in pixels.',
    },
    {
      key: 'visualMap.itemWidth',
      label: 'Item Width',
      path: 'visualMap.$visualMapIndex.itemWidth',
      control: 'number',
      defaultValue: 20,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Controller width in pixels.',
    },
    {
      key: 'visualMap.itemHeight',
      label: 'Item Height',
      path: 'visualMap.$visualMapIndex.itemHeight',
      control: 'number',
      defaultValue: 140,
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'Layout',
      helpText: 'Controller height in pixels.',
    },
    {
      key: 'visualMap.splitNumber',
      label: 'Split Number',
      path: 'visualMap.$visualMapIndex.splitNumber',
      control: 'number',
      defaultValue: 5,
      visibleWhen: isPiecewiseVisualMap,
      complexity: 'advanced',
      group: 'Piecewise',
      helpText: 'Number of intervals for piecewise mapping.',
    },
    {
      key: 'visualMap.selectedMode',
      label: 'Selected Mode',
      path: 'visualMap.$visualMapIndex.selectedMode',
      control: 'select',
      defaultValue: 'multiple',
      visibleWhen: isPiecewiseVisualMap,
      complexity: 'advanced',
      group: 'Piecewise',
      helpText: 'Selection behavior for piecewise blocks.',
      options: [
        { label: 'Multiple', value: 'multiple' },
        { label: 'Single', value: 'single' },
        { label: 'None', value: 'false' },
      ],
    },
    {
      key: 'visualMap.itemGap',
      label: 'Item Gap',
      path: 'visualMap.$visualMapIndex.itemGap',
      control: 'number',
      defaultValue: 10,
      visibleWhen: isPiecewiseVisualMap,
      complexity: 'advanced',
      group: 'Piecewise',
      helpText: 'Gap between piecewise items in pixels.',
    },
    {
      key: 'visualMap.showLabel',
      label: 'Show Label',
      path: 'visualMap.$visualMapIndex.showLabel',
      control: 'checkbox',
      defaultValue: true,
      visibleWhen: isPiecewiseVisualMap,
      complexity: 'advanced',
      group: 'Piecewise',
      helpText: 'Show text labels for piecewise intervals.',
    },
    {
      key: 'visualMap.minOpen',
      label: 'Min Open',
      path: 'visualMap.$visualMapIndex.minOpen',
      control: 'checkbox',
      defaultValue: false,
      visibleWhen: isPiecewiseVisualMap,
      complexity: 'advanced',
      group: 'Piecewise',
      helpText: 'Create open-ended interval below minimum.',
    },
    {
      key: 'visualMap.maxOpen',
      label: 'Max Open',
      path: 'visualMap.$visualMapIndex.maxOpen',
      control: 'checkbox',
      defaultValue: false,
      visibleWhen: isPiecewiseVisualMap,
      complexity: 'advanced',
      group: 'Piecewise',
      helpText: 'Create open-ended interval above maximum.',
    },
    {
      key: 'visualMap.inRange.color',
      label: 'In Range Colors',
      path: 'visualMap.$visualMapIndex.inRange.color',
      control: 'textarea',
      valueEditor: 'color-array',
      defaultValue: ['#50a3ba', '#eac736', '#d94e5d'],
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'In / Out Range',
      helpText: 'Gradient or list of colors used for mapped values.',
    },
    {
      key: 'visualMap.inRange.symbolSize',
      label: 'In Range Symbol Size',
      path: 'visualMap.$visualMapIndex.inRange.symbolSize',
      control: 'textarea',
      valueEditor: 'number-array',
      defaultValue: [10, 50],
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'In / Out Range',
      helpText: 'Symbol size range for in-range values (one number per line).',
      placeholder: '10\n50',
    },
    {
      key: 'visualMap.outOfRange.color',
      label: 'Out Of Range Colors',
      path: 'visualMap.$visualMapIndex.outOfRange.color',
      control: 'textarea',
      valueEditor: 'color-array',
      defaultValue: ['#94a3b8'],
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'In / Out Range',
      helpText: 'Colors used for out-of-range values.',
    },
    {
      key: 'visualMap.outOfRange.symbolSize',
      label: 'Out Of Range Symbol Size',
      path: 'visualMap.$visualMapIndex.outOfRange.symbolSize',
      control: 'textarea',
      valueEditor: 'number-array',
      defaultValue: [6, 18],
      visibleWhen: supportsVisualMap,
      complexity: 'advanced',
      group: 'In / Out Range',
      helpText: 'Symbol size range for out-of-range values (one number per line).',
      placeholder: '6\n18',
    },
    ...createTextStyleFields({
      keyPrefix: 'visualMap.textStyle',
      pathPrefix: 'visualMap.$visualMapIndex.textStyle',
      labelPrefix: 'Text',
      defaultColor: '#e2e8f0',
      defaultFontSize: 12,
      visibleWhen: supportsVisualMap,
    }).map((field): FieldSchema => ({
      ...field,
      complexity: 'advanced',
      group: 'Style',
    })),
    ...createBoxModelFields({
      keyPrefix: 'visualMap',
      pathPrefix: 'visualMap.$visualMapIndex',
      defaultBackgroundColor: 'transparent',
      defaultBorderColor: '#000000',
      defaultBorderWidth: 0,
      defaultPadding: 8,
      visibleWhen: supportsVisualMap,
    }).map((field): FieldSchema => ({
      ...field,
      complexity: 'advanced',
      group: 'Style',
    })),
];

export const visualMapSection: SectionSchema = {
  id: 'visualMap',
  title: 'VisualMap',
  arrayBinding: {
    id: 'visualMap',
    path: 'visualMap',
    indexToken: '$visualMapIndex',
    itemLabel: 'VisualMap',
    defaultItem: defaultVisualMapItem,
    minItems: 0,
  },
  fields: visualMapFields,
};
